package ht.mappergenerator.mapper108;

import ht.model.model108.FactoryResourceBases;
import ht.model.model108.FactoryResourceBasesExample;
import ht.model.model108.FactoryResourceBasesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FactoryResourceBasesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int countByExample(FactoryResourceBasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int deleteByExample(FactoryResourceBasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int insert(FactoryResourceBasesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int insertSelective(FactoryResourceBasesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    List<FactoryResourceBasesWithBLOBs> selectByExampleWithBLOBs(FactoryResourceBasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    List<FactoryResourceBases> selectByExample(FactoryResourceBasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    FactoryResourceBasesWithBLOBs selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByExampleSelective(@Param("record") FactoryResourceBasesWithBLOBs record, @Param("example") FactoryResourceBasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") FactoryResourceBasesWithBLOBs record, @Param("example") FactoryResourceBasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByExample(@Param("record") FactoryResourceBases record, @Param("example") FactoryResourceBasesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByPrimaryKeySelective(FactoryResourceBasesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(FactoryResourceBasesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FactoryResourceBases
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByPrimaryKey(FactoryResourceBases record);
}