package ht.mappergenerator.mapper108;

import ht.model.model108.ItemInventories;
import ht.model.model108.ItemInventoriesExample;
import ht.model.model108.ItemInventoriesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemInventoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int countByExample(ItemInventoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int deleteByExample(ItemInventoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int insert(ItemInventoriesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int insertSelective(ItemInventoriesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    List<ItemInventoriesWithBLOBs> selectByExampleWithBLOBs(ItemInventoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    List<ItemInventories> selectByExample(ItemInventoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    ItemInventoriesWithBLOBs selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByExampleSelective(@Param("record") ItemInventoriesWithBLOBs record, @Param("example") ItemInventoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") ItemInventoriesWithBLOBs record, @Param("example") ItemInventoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByExample(@Param("record") ItemInventories record, @Param("example") ItemInventoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByPrimaryKeySelective(ItemInventoriesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(ItemInventoriesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventories
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByPrimaryKey(ItemInventories record);
}