package ht.mappergenerator.mapper108;

import ht.model.model108.ItemTypes;
import ht.model.model108.ItemTypesExample;
import ht.model.model108.ItemTypesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemTypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int countByExample(ItemTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int deleteByExample(ItemTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int insert(ItemTypesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int insertSelective(ItemTypesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    List<ItemTypesWithBLOBs> selectByExampleWithBLOBs(ItemTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    List<ItemTypes> selectByExample(ItemTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    ItemTypesWithBLOBs selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByExampleSelective(@Param("record") ItemTypesWithBLOBs record, @Param("example") ItemTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") ItemTypesWithBLOBs record, @Param("example") ItemTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByExample(@Param("record") ItemTypes record, @Param("example") ItemTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByPrimaryKeySelective(ItemTypesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(ItemTypesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemTypes
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByPrimaryKey(ItemTypes record);
}