package ht.mappergenerator.mapper108;

import ht.model.model108.StockLocations;
import ht.model.model108.StockLocationsExample;
import ht.model.model108.StockLocationsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockLocationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int countByExample(StockLocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int deleteByExample(StockLocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int insert(StockLocationsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int insertSelective(StockLocationsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    List<StockLocationsWithBLOBs> selectByExampleWithBLOBs(StockLocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    List<StockLocations> selectByExample(StockLocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    StockLocationsWithBLOBs selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByExampleSelective(@Param("record") StockLocationsWithBLOBs record, @Param("example") StockLocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") StockLocationsWithBLOBs record, @Param("example") StockLocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByExample(@Param("record") StockLocations record, @Param("example") StockLocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByPrimaryKeySelective(StockLocationsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(StockLocationsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table StockLocations
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    int updateByPrimaryKey(StockLocations record);
}