package ht.mappergenerator.mapper131;

import ht.model.model131.ItemInventoryHistories;
import ht.model.model131.ItemInventoryHistoriesExample;
import ht.model.model131.ItemInventoryHistoriesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemInventoryHistoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int countByExample(ItemInventoryHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int deleteByExample(ItemInventoryHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int deleteByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int insert(ItemInventoryHistoriesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int insertSelective(ItemInventoryHistoriesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    List<ItemInventoryHistoriesWithBLOBs> selectByExampleWithBLOBs(ItemInventoryHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    List<ItemInventoryHistories> selectByExample(ItemInventoryHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    ItemInventoryHistoriesWithBLOBs selectByPrimaryKey(String ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int updateByExampleSelective(@Param("record") ItemInventoryHistoriesWithBLOBs record, @Param("example") ItemInventoryHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") ItemInventoryHistoriesWithBLOBs record, @Param("example") ItemInventoryHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int updateByExample(@Param("record") ItemInventoryHistories record, @Param("example") ItemInventoryHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int updateByPrimaryKeySelective(ItemInventoryHistoriesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(ItemInventoryHistoriesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ItemInventoryHistories
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int updateByPrimaryKey(ItemInventoryHistories record);
}