package ht.mappergenerator.mapper131;

import ht.model.model131.UID_xTend_MaterialTransactionsRHDCDW;
import ht.model.model131.UID_xTend_MaterialTransactionsRHDCDWExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UID_xTend_MaterialTransactionsRHDCDWMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int countByExample(UID_xTend_MaterialTransactionsRHDCDWExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int deleteByExample(UID_xTend_MaterialTransactionsRHDCDWExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int deleteByPrimaryKey(String transactionHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int insert(UID_xTend_MaterialTransactionsRHDCDW record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int insertSelective(UID_xTend_MaterialTransactionsRHDCDW record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    List<UID_xTend_MaterialTransactionsRHDCDW> selectByExampleWithBLOBs(UID_xTend_MaterialTransactionsRHDCDWExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    List<UID_xTend_MaterialTransactionsRHDCDW> selectByExample(UID_xTend_MaterialTransactionsRHDCDWExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    UID_xTend_MaterialTransactionsRHDCDW selectByPrimaryKey(String transactionHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int updateByExampleSelective(@Param("record") UID_xTend_MaterialTransactionsRHDCDW record, @Param("example") UID_xTend_MaterialTransactionsRHDCDWExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") UID_xTend_MaterialTransactionsRHDCDW record, @Param("example") UID_xTend_MaterialTransactionsRHDCDWExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int updateByExample(@Param("record") UID_xTend_MaterialTransactionsRHDCDW record, @Param("example") UID_xTend_MaterialTransactionsRHDCDWExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int updateByPrimaryKeySelective(UID_xTend_MaterialTransactionsRHDCDW record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(UID_xTend_MaterialTransactionsRHDCDW record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    int updateByPrimaryKey(UID_xTend_MaterialTransactionsRHDCDW record);
}