package ht.model.model131;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UID_xTend_MaterialTransactionsRHDCDWExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public UID_xTend_MaterialTransactionsRHDCDWExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTransactionHistoryIdIsNull() {
            addCriterion("TransactionHistoryId is null");
            return (Criteria) this;
        }

        public Criteria andTransactionHistoryIdIsNotNull() {
            addCriterion("TransactionHistoryId is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionHistoryIdEqualTo(String value) {
            addCriterion("TransactionHistoryId =", value, "transactionHistoryId");
            return (Criteria) this;
        }

        public Criteria andTransactionHistoryIdNotEqualTo(String value) {
            addCriterion("TransactionHistoryId <>", value, "transactionHistoryId");
            return (Criteria) this;
        }

        public Criteria andTransactionHistoryIdGreaterThan(String value) {
            addCriterion("TransactionHistoryId >", value, "transactionHistoryId");
            return (Criteria) this;
        }

        public Criteria andTransactionHistoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("TransactionHistoryId >=", value, "transactionHistoryId");
            return (Criteria) this;
        }

        public Criteria andTransactionHistoryIdLessThan(String value) {
            addCriterion("TransactionHistoryId <", value, "transactionHistoryId");
            return (Criteria) this;
        }

        public Criteria andTransactionHistoryIdLessThanOrEqualTo(String value) {
            addCriterion("TransactionHistoryId <=", value, "transactionHistoryId");
            return (Criteria) this;
        }

        public Criteria andTransactionHistoryIdLike(String value) {
            addCriterion("TransactionHistoryId like", value, "transactionHistoryId");
            return (Criteria) this;
        }

        public Criteria andTransactionHistoryIdNotLike(String value) {
            addCriterion("TransactionHistoryId not like", value, "transactionHistoryId");
            return (Criteria) this;
        }

        public Criteria andTransactionHistoryIdIn(List<String> values) {
            addCriterion("TransactionHistoryId in", values, "transactionHistoryId");
            return (Criteria) this;
        }

        public Criteria andTransactionHistoryIdNotIn(List<String> values) {
            addCriterion("TransactionHistoryId not in", values, "transactionHistoryId");
            return (Criteria) this;
        }

        public Criteria andTransactionHistoryIdBetween(String value1, String value2) {
            addCriterion("TransactionHistoryId between", value1, value2, "transactionHistoryId");
            return (Criteria) this;
        }

        public Criteria andTransactionHistoryIdNotBetween(String value1, String value2) {
            addCriterion("TransactionHistoryId not between", value1, value2, "transactionHistoryId");
            return (Criteria) this;
        }

        public Criteria andUIDIsNull() {
            addCriterion("UID is null");
            return (Criteria) this;
        }

        public Criteria andUIDIsNotNull() {
            addCriterion("UID is not null");
            return (Criteria) this;
        }

        public Criteria andUIDEqualTo(String value) {
            addCriterion("UID =", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotEqualTo(String value) {
            addCriterion("UID <>", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDGreaterThan(String value) {
            addCriterion("UID >", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDGreaterThanOrEqualTo(String value) {
            addCriterion("UID >=", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDLessThan(String value) {
            addCriterion("UID <", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDLessThanOrEqualTo(String value) {
            addCriterion("UID <=", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDLike(String value) {
            addCriterion("UID like", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotLike(String value) {
            addCriterion("UID not like", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDIn(List<String> values) {
            addCriterion("UID in", values, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotIn(List<String> values) {
            addCriterion("UID not in", values, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDBetween(String value1, String value2) {
            addCriterion("UID between", value1, value2, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotBetween(String value1, String value2) {
            addCriterion("UID not between", value1, value2, "UID");
            return (Criteria) this;
        }

        public Criteria andBatchIsNull() {
            addCriterion("Batch is null");
            return (Criteria) this;
        }

        public Criteria andBatchIsNotNull() {
            addCriterion("Batch is not null");
            return (Criteria) this;
        }

        public Criteria andBatchEqualTo(String value) {
            addCriterion("Batch =", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotEqualTo(String value) {
            addCriterion("Batch <>", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchGreaterThan(String value) {
            addCriterion("Batch >", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchGreaterThanOrEqualTo(String value) {
            addCriterion("Batch >=", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLessThan(String value) {
            addCriterion("Batch <", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLessThanOrEqualTo(String value) {
            addCriterion("Batch <=", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLike(String value) {
            addCriterion("Batch like", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotLike(String value) {
            addCriterion("Batch not like", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchIn(List<String> values) {
            addCriterion("Batch in", values, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotIn(List<String> values) {
            addCriterion("Batch not in", values, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchBetween(String value1, String value2) {
            addCriterion("Batch between", value1, value2, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotBetween(String value1, String value2) {
            addCriterion("Batch not between", value1, value2, "batch");
            return (Criteria) this;
        }

        public Criteria andPartNumberIsNull() {
            addCriterion("PartNumber is null");
            return (Criteria) this;
        }

        public Criteria andPartNumberIsNotNull() {
            addCriterion("PartNumber is not null");
            return (Criteria) this;
        }

        public Criteria andPartNumberEqualTo(String value) {
            addCriterion("PartNumber =", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotEqualTo(String value) {
            addCriterion("PartNumber <>", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberGreaterThan(String value) {
            addCriterion("PartNumber >", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberGreaterThanOrEqualTo(String value) {
            addCriterion("PartNumber >=", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberLessThan(String value) {
            addCriterion("PartNumber <", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberLessThanOrEqualTo(String value) {
            addCriterion("PartNumber <=", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberLike(String value) {
            addCriterion("PartNumber like", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotLike(String value) {
            addCriterion("PartNumber not like", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberIn(List<String> values) {
            addCriterion("PartNumber in", values, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotIn(List<String> values) {
            addCriterion("PartNumber not in", values, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberBetween(String value1, String value2) {
            addCriterion("PartNumber between", value1, value2, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotBetween(String value1, String value2) {
            addCriterion("PartNumber not between", value1, value2, "partNumber");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("Quantity is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("Quantity is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(Double value) {
            addCriterion("Quantity =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(Double value) {
            addCriterion("Quantity <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(Double value) {
            addCriterion("Quantity >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(Double value) {
            addCriterion("Quantity >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(Double value) {
            addCriterion("Quantity <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(Double value) {
            addCriterion("Quantity <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<Double> values) {
            addCriterion("Quantity in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<Double> values) {
            addCriterion("Quantity not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(Double value1, Double value2) {
            addCriterion("Quantity between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(Double value1, Double value2) {
            addCriterion("Quantity not between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andUOMIsNull() {
            addCriterion("UOM is null");
            return (Criteria) this;
        }

        public Criteria andUOMIsNotNull() {
            addCriterion("UOM is not null");
            return (Criteria) this;
        }

        public Criteria andUOMEqualTo(String value) {
            addCriterion("UOM =", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMNotEqualTo(String value) {
            addCriterion("UOM <>", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMGreaterThan(String value) {
            addCriterion("UOM >", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMGreaterThanOrEqualTo(String value) {
            addCriterion("UOM >=", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMLessThan(String value) {
            addCriterion("UOM <", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMLessThanOrEqualTo(String value) {
            addCriterion("UOM <=", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMLike(String value) {
            addCriterion("UOM like", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMNotLike(String value) {
            addCriterion("UOM not like", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMIn(List<String> values) {
            addCriterion("UOM in", values, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMNotIn(List<String> values) {
            addCriterion("UOM not in", values, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMBetween(String value1, String value2) {
            addCriterion("UOM between", value1, value2, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMNotBetween(String value1, String value2) {
            addCriterion("UOM not between", value1, value2, "UOM");
            return (Criteria) this;
        }

        public Criteria andResultStatusIsNull() {
            addCriterion("ResultStatus is null");
            return (Criteria) this;
        }

        public Criteria andResultStatusIsNotNull() {
            addCriterion("ResultStatus is not null");
            return (Criteria) this;
        }

        public Criteria andResultStatusEqualTo(Integer value) {
            addCriterion("ResultStatus =", value, "resultStatus");
            return (Criteria) this;
        }

        public Criteria andResultStatusNotEqualTo(Integer value) {
            addCriterion("ResultStatus <>", value, "resultStatus");
            return (Criteria) this;
        }

        public Criteria andResultStatusGreaterThan(Integer value) {
            addCriterion("ResultStatus >", value, "resultStatus");
            return (Criteria) this;
        }

        public Criteria andResultStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("ResultStatus >=", value, "resultStatus");
            return (Criteria) this;
        }

        public Criteria andResultStatusLessThan(Integer value) {
            addCriterion("ResultStatus <", value, "resultStatus");
            return (Criteria) this;
        }

        public Criteria andResultStatusLessThanOrEqualTo(Integer value) {
            addCriterion("ResultStatus <=", value, "resultStatus");
            return (Criteria) this;
        }

        public Criteria andResultStatusIn(List<Integer> values) {
            addCriterion("ResultStatus in", values, "resultStatus");
            return (Criteria) this;
        }

        public Criteria andResultStatusNotIn(List<Integer> values) {
            addCriterion("ResultStatus not in", values, "resultStatus");
            return (Criteria) this;
        }

        public Criteria andResultStatusBetween(Integer value1, Integer value2) {
            addCriterion("ResultStatus between", value1, value2, "resultStatus");
            return (Criteria) this;
        }

        public Criteria andResultStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("ResultStatus not between", value1, value2, "resultStatus");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputIsNull() {
            addCriterion("FromStock_Input is null");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputIsNotNull() {
            addCriterion("FromStock_Input is not null");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputEqualTo(String value) {
            addCriterion("FromStock_Input =", value, "fromStock_Input");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputNotEqualTo(String value) {
            addCriterion("FromStock_Input <>", value, "fromStock_Input");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputGreaterThan(String value) {
            addCriterion("FromStock_Input >", value, "fromStock_Input");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputGreaterThanOrEqualTo(String value) {
            addCriterion("FromStock_Input >=", value, "fromStock_Input");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputLessThan(String value) {
            addCriterion("FromStock_Input <", value, "fromStock_Input");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputLessThanOrEqualTo(String value) {
            addCriterion("FromStock_Input <=", value, "fromStock_Input");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputLike(String value) {
            addCriterion("FromStock_Input like", value, "fromStock_Input");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputNotLike(String value) {
            addCriterion("FromStock_Input not like", value, "fromStock_Input");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputIn(List<String> values) {
            addCriterion("FromStock_Input in", values, "fromStock_Input");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputNotIn(List<String> values) {
            addCriterion("FromStock_Input not in", values, "fromStock_Input");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputBetween(String value1, String value2) {
            addCriterion("FromStock_Input between", value1, value2, "fromStock_Input");
            return (Criteria) this;
        }

        public Criteria andFromStock_InputNotBetween(String value1, String value2) {
            addCriterion("FromStock_Input not between", value1, value2, "fromStock_Input");
            return (Criteria) this;
        }

        public Criteria andFromStockIsNull() {
            addCriterion("FromStock is null");
            return (Criteria) this;
        }

        public Criteria andFromStockIsNotNull() {
            addCriterion("FromStock is not null");
            return (Criteria) this;
        }

        public Criteria andFromStockEqualTo(String value) {
            addCriterion("FromStock =", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockNotEqualTo(String value) {
            addCriterion("FromStock <>", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockGreaterThan(String value) {
            addCriterion("FromStock >", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockGreaterThanOrEqualTo(String value) {
            addCriterion("FromStock >=", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockLessThan(String value) {
            addCriterion("FromStock <", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockLessThanOrEqualTo(String value) {
            addCriterion("FromStock <=", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockLike(String value) {
            addCriterion("FromStock like", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockNotLike(String value) {
            addCriterion("FromStock not like", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockIn(List<String> values) {
            addCriterion("FromStock in", values, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockNotIn(List<String> values) {
            addCriterion("FromStock not in", values, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockBetween(String value1, String value2) {
            addCriterion("FromStock between", value1, value2, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockNotBetween(String value1, String value2) {
            addCriterion("FromStock not between", value1, value2, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinIsNull() {
            addCriterion("FromStock_Bin is null");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinIsNotNull() {
            addCriterion("FromStock_Bin is not null");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinEqualTo(String value) {
            addCriterion("FromStock_Bin =", value, "fromStock_Bin");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinNotEqualTo(String value) {
            addCriterion("FromStock_Bin <>", value, "fromStock_Bin");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinGreaterThan(String value) {
            addCriterion("FromStock_Bin >", value, "fromStock_Bin");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinGreaterThanOrEqualTo(String value) {
            addCriterion("FromStock_Bin >=", value, "fromStock_Bin");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinLessThan(String value) {
            addCriterion("FromStock_Bin <", value, "fromStock_Bin");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinLessThanOrEqualTo(String value) {
            addCriterion("FromStock_Bin <=", value, "fromStock_Bin");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinLike(String value) {
            addCriterion("FromStock_Bin like", value, "fromStock_Bin");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinNotLike(String value) {
            addCriterion("FromStock_Bin not like", value, "fromStock_Bin");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinIn(List<String> values) {
            addCriterion("FromStock_Bin in", values, "fromStock_Bin");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinNotIn(List<String> values) {
            addCriterion("FromStock_Bin not in", values, "fromStock_Bin");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinBetween(String value1, String value2) {
            addCriterion("FromStock_Bin between", value1, value2, "fromStock_Bin");
            return (Criteria) this;
        }

        public Criteria andFromStock_BinNotBetween(String value1, String value2) {
            addCriterion("FromStock_Bin not between", value1, value2, "fromStock_Bin");
            return (Criteria) this;
        }

        public Criteria andToStock_InputIsNull() {
            addCriterion("ToStock_Input is null");
            return (Criteria) this;
        }

        public Criteria andToStock_InputIsNotNull() {
            addCriterion("ToStock_Input is not null");
            return (Criteria) this;
        }

        public Criteria andToStock_InputEqualTo(String value) {
            addCriterion("ToStock_Input =", value, "toStock_Input");
            return (Criteria) this;
        }

        public Criteria andToStock_InputNotEqualTo(String value) {
            addCriterion("ToStock_Input <>", value, "toStock_Input");
            return (Criteria) this;
        }

        public Criteria andToStock_InputGreaterThan(String value) {
            addCriterion("ToStock_Input >", value, "toStock_Input");
            return (Criteria) this;
        }

        public Criteria andToStock_InputGreaterThanOrEqualTo(String value) {
            addCriterion("ToStock_Input >=", value, "toStock_Input");
            return (Criteria) this;
        }

        public Criteria andToStock_InputLessThan(String value) {
            addCriterion("ToStock_Input <", value, "toStock_Input");
            return (Criteria) this;
        }

        public Criteria andToStock_InputLessThanOrEqualTo(String value) {
            addCriterion("ToStock_Input <=", value, "toStock_Input");
            return (Criteria) this;
        }

        public Criteria andToStock_InputLike(String value) {
            addCriterion("ToStock_Input like", value, "toStock_Input");
            return (Criteria) this;
        }

        public Criteria andToStock_InputNotLike(String value) {
            addCriterion("ToStock_Input not like", value, "toStock_Input");
            return (Criteria) this;
        }

        public Criteria andToStock_InputIn(List<String> values) {
            addCriterion("ToStock_Input in", values, "toStock_Input");
            return (Criteria) this;
        }

        public Criteria andToStock_InputNotIn(List<String> values) {
            addCriterion("ToStock_Input not in", values, "toStock_Input");
            return (Criteria) this;
        }

        public Criteria andToStock_InputBetween(String value1, String value2) {
            addCriterion("ToStock_Input between", value1, value2, "toStock_Input");
            return (Criteria) this;
        }

        public Criteria andToStock_InputNotBetween(String value1, String value2) {
            addCriterion("ToStock_Input not between", value1, value2, "toStock_Input");
            return (Criteria) this;
        }

        public Criteria andToStockIsNull() {
            addCriterion("ToStock is null");
            return (Criteria) this;
        }

        public Criteria andToStockIsNotNull() {
            addCriterion("ToStock is not null");
            return (Criteria) this;
        }

        public Criteria andToStockEqualTo(String value) {
            addCriterion("ToStock =", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockNotEqualTo(String value) {
            addCriterion("ToStock <>", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockGreaterThan(String value) {
            addCriterion("ToStock >", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockGreaterThanOrEqualTo(String value) {
            addCriterion("ToStock >=", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockLessThan(String value) {
            addCriterion("ToStock <", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockLessThanOrEqualTo(String value) {
            addCriterion("ToStock <=", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockLike(String value) {
            addCriterion("ToStock like", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockNotLike(String value) {
            addCriterion("ToStock not like", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockIn(List<String> values) {
            addCriterion("ToStock in", values, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockNotIn(List<String> values) {
            addCriterion("ToStock not in", values, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockBetween(String value1, String value2) {
            addCriterion("ToStock between", value1, value2, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockNotBetween(String value1, String value2) {
            addCriterion("ToStock not between", value1, value2, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStock_BinIsNull() {
            addCriterion("ToStock_Bin is null");
            return (Criteria) this;
        }

        public Criteria andToStock_BinIsNotNull() {
            addCriterion("ToStock_Bin is not null");
            return (Criteria) this;
        }

        public Criteria andToStock_BinEqualTo(String value) {
            addCriterion("ToStock_Bin =", value, "toStock_Bin");
            return (Criteria) this;
        }

        public Criteria andToStock_BinNotEqualTo(String value) {
            addCriterion("ToStock_Bin <>", value, "toStock_Bin");
            return (Criteria) this;
        }

        public Criteria andToStock_BinGreaterThan(String value) {
            addCriterion("ToStock_Bin >", value, "toStock_Bin");
            return (Criteria) this;
        }

        public Criteria andToStock_BinGreaterThanOrEqualTo(String value) {
            addCriterion("ToStock_Bin >=", value, "toStock_Bin");
            return (Criteria) this;
        }

        public Criteria andToStock_BinLessThan(String value) {
            addCriterion("ToStock_Bin <", value, "toStock_Bin");
            return (Criteria) this;
        }

        public Criteria andToStock_BinLessThanOrEqualTo(String value) {
            addCriterion("ToStock_Bin <=", value, "toStock_Bin");
            return (Criteria) this;
        }

        public Criteria andToStock_BinLike(String value) {
            addCriterion("ToStock_Bin like", value, "toStock_Bin");
            return (Criteria) this;
        }

        public Criteria andToStock_BinNotLike(String value) {
            addCriterion("ToStock_Bin not like", value, "toStock_Bin");
            return (Criteria) this;
        }

        public Criteria andToStock_BinIn(List<String> values) {
            addCriterion("ToStock_Bin in", values, "toStock_Bin");
            return (Criteria) this;
        }

        public Criteria andToStock_BinNotIn(List<String> values) {
            addCriterion("ToStock_Bin not in", values, "toStock_Bin");
            return (Criteria) this;
        }

        public Criteria andToStock_BinBetween(String value1, String value2) {
            addCriterion("ToStock_Bin between", value1, value2, "toStock_Bin");
            return (Criteria) this;
        }

        public Criteria andToStock_BinNotBetween(String value1, String value2) {
            addCriterion("ToStock_Bin not between", value1, value2, "toStock_Bin");
            return (Criteria) this;
        }

        public Criteria andTransactionUserIsNull() {
            addCriterion("TransactionUser is null");
            return (Criteria) this;
        }

        public Criteria andTransactionUserIsNotNull() {
            addCriterion("TransactionUser is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionUserEqualTo(String value) {
            addCriterion("TransactionUser =", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserNotEqualTo(String value) {
            addCriterion("TransactionUser <>", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserGreaterThan(String value) {
            addCriterion("TransactionUser >", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserGreaterThanOrEqualTo(String value) {
            addCriterion("TransactionUser >=", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserLessThan(String value) {
            addCriterion("TransactionUser <", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserLessThanOrEqualTo(String value) {
            addCriterion("TransactionUser <=", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserLike(String value) {
            addCriterion("TransactionUser like", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserNotLike(String value) {
            addCriterion("TransactionUser not like", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserIn(List<String> values) {
            addCriterion("TransactionUser in", values, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserNotIn(List<String> values) {
            addCriterion("TransactionUser not in", values, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserBetween(String value1, String value2) {
            addCriterion("TransactionUser between", value1, value2, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserNotBetween(String value1, String value2) {
            addCriterion("TransactionUser not between", value1, value2, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeIsNull() {
            addCriterion("TransactionTime is null");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeIsNotNull() {
            addCriterion("TransactionTime is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeEqualTo(Date value) {
            addCriterion("TransactionTime =", value, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeNotEqualTo(Date value) {
            addCriterion("TransactionTime <>", value, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeGreaterThan(Date value) {
            addCriterion("TransactionTime >", value, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("TransactionTime >=", value, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeLessThan(Date value) {
            addCriterion("TransactionTime <", value, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeLessThanOrEqualTo(Date value) {
            addCriterion("TransactionTime <=", value, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeIn(List<Date> values) {
            addCriterion("TransactionTime in", values, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeNotIn(List<Date> values) {
            addCriterion("TransactionTime not in", values, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeBetween(Date value1, Date value2) {
            addCriterion("TransactionTime between", value1, value2, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeNotBetween(Date value1, Date value2) {
            addCriterion("TransactionTime not between", value1, value2, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1IsNull() {
            addCriterion("TransactionUser_1 is null");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1IsNotNull() {
            addCriterion("TransactionUser_1 is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1EqualTo(String value) {
            addCriterion("TransactionUser_1 =", value, "transactionUser_1");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1NotEqualTo(String value) {
            addCriterion("TransactionUser_1 <>", value, "transactionUser_1");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1GreaterThan(String value) {
            addCriterion("TransactionUser_1 >", value, "transactionUser_1");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1GreaterThanOrEqualTo(String value) {
            addCriterion("TransactionUser_1 >=", value, "transactionUser_1");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1LessThan(String value) {
            addCriterion("TransactionUser_1 <", value, "transactionUser_1");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1LessThanOrEqualTo(String value) {
            addCriterion("TransactionUser_1 <=", value, "transactionUser_1");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1Like(String value) {
            addCriterion("TransactionUser_1 like", value, "transactionUser_1");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1NotLike(String value) {
            addCriterion("TransactionUser_1 not like", value, "transactionUser_1");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1In(List<String> values) {
            addCriterion("TransactionUser_1 in", values, "transactionUser_1");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1NotIn(List<String> values) {
            addCriterion("TransactionUser_1 not in", values, "transactionUser_1");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1Between(String value1, String value2) {
            addCriterion("TransactionUser_1 between", value1, value2, "transactionUser_1");
            return (Criteria) this;
        }

        public Criteria andTransactionUser_1NotBetween(String value1, String value2) {
            addCriterion("TransactionUser_1 not between", value1, value2, "transactionUser_1");
            return (Criteria) this;
        }

        public Criteria andTransactionTime_1IsNull() {
            addCriterion("TransactionTime_1 is null");
            return (Criteria) this;
        }

        public Criteria andTransactionTime_1IsNotNull() {
            addCriterion("TransactionTime_1 is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionTime_1EqualTo(Date value) {
            addCriterion("TransactionTime_1 =", value, "transactionTime_1");
            return (Criteria) this;
        }

        public Criteria andTransactionTime_1NotEqualTo(Date value) {
            addCriterion("TransactionTime_1 <>", value, "transactionTime_1");
            return (Criteria) this;
        }

        public Criteria andTransactionTime_1GreaterThan(Date value) {
            addCriterion("TransactionTime_1 >", value, "transactionTime_1");
            return (Criteria) this;
        }

        public Criteria andTransactionTime_1GreaterThanOrEqualTo(Date value) {
            addCriterion("TransactionTime_1 >=", value, "transactionTime_1");
            return (Criteria) this;
        }

        public Criteria andTransactionTime_1LessThan(Date value) {
            addCriterion("TransactionTime_1 <", value, "transactionTime_1");
            return (Criteria) this;
        }

        public Criteria andTransactionTime_1LessThanOrEqualTo(Date value) {
            addCriterion("TransactionTime_1 <=", value, "transactionTime_1");
            return (Criteria) this;
        }

        public Criteria andTransactionTime_1In(List<Date> values) {
            addCriterion("TransactionTime_1 in", values, "transactionTime_1");
            return (Criteria) this;
        }

        public Criteria andTransactionTime_1NotIn(List<Date> values) {
            addCriterion("TransactionTime_1 not in", values, "transactionTime_1");
            return (Criteria) this;
        }

        public Criteria andTransactionTime_1Between(Date value1, Date value2) {
            addCriterion("TransactionTime_1 between", value1, value2, "transactionTime_1");
            return (Criteria) this;
        }

        public Criteria andTransactionTime_1NotBetween(Date value1, Date value2) {
            addCriterion("TransactionTime_1 not between", value1, value2, "transactionTime_1");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIsNull() {
            addCriterion("TransactionType is null");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIsNotNull() {
            addCriterion("TransactionType is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeEqualTo(String value) {
            addCriterion("TransactionType =", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotEqualTo(String value) {
            addCriterion("TransactionType <>", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeGreaterThan(String value) {
            addCriterion("TransactionType >", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TransactionType >=", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLessThan(String value) {
            addCriterion("TransactionType <", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLessThanOrEqualTo(String value) {
            addCriterion("TransactionType <=", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLike(String value) {
            addCriterion("TransactionType like", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotLike(String value) {
            addCriterion("TransactionType not like", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIn(List<String> values) {
            addCriterion("TransactionType in", values, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotIn(List<String> values) {
            addCriterion("TransactionType not in", values, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeBetween(String value1, String value2) {
            addCriterion("TransactionType between", value1, value2, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotBetween(String value1, String value2) {
            addCriterion("TransactionType not between", value1, value2, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonIsNull() {
            addCriterion("TransactionReason is null");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonIsNotNull() {
            addCriterion("TransactionReason is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonEqualTo(String value) {
            addCriterion("TransactionReason =", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonNotEqualTo(String value) {
            addCriterion("TransactionReason <>", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonGreaterThan(String value) {
            addCriterion("TransactionReason >", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonGreaterThanOrEqualTo(String value) {
            addCriterion("TransactionReason >=", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonLessThan(String value) {
            addCriterion("TransactionReason <", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonLessThanOrEqualTo(String value) {
            addCriterion("TransactionReason <=", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonLike(String value) {
            addCriterion("TransactionReason like", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonNotLike(String value) {
            addCriterion("TransactionReason not like", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonIn(List<String> values) {
            addCriterion("TransactionReason in", values, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonNotIn(List<String> values) {
            addCriterion("TransactionReason not in", values, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonBetween(String value1, String value2) {
            addCriterion("TransactionReason between", value1, value2, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonNotBetween(String value1, String value2) {
            addCriterion("TransactionReason not between", value1, value2, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDIsNull() {
            addCriterion("RFCTemplateID is null");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDIsNotNull() {
            addCriterion("RFCTemplateID is not null");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDEqualTo(String value) {
            addCriterion("RFCTemplateID =", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDNotEqualTo(String value) {
            addCriterion("RFCTemplateID <>", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDGreaterThan(String value) {
            addCriterion("RFCTemplateID >", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDGreaterThanOrEqualTo(String value) {
            addCriterion("RFCTemplateID >=", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDLessThan(String value) {
            addCriterion("RFCTemplateID <", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDLessThanOrEqualTo(String value) {
            addCriterion("RFCTemplateID <=", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDLike(String value) {
            addCriterion("RFCTemplateID like", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDNotLike(String value) {
            addCriterion("RFCTemplateID not like", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDIn(List<String> values) {
            addCriterion("RFCTemplateID in", values, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDNotIn(List<String> values) {
            addCriterion("RFCTemplateID not in", values, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDBetween(String value1, String value2) {
            addCriterion("RFCTemplateID between", value1, value2, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDNotBetween(String value1, String value2) {
            addCriterion("RFCTemplateID not between", value1, value2, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRefDocNoIsNull() {
            addCriterion("RefDocNo is null");
            return (Criteria) this;
        }

        public Criteria andRefDocNoIsNotNull() {
            addCriterion("RefDocNo is not null");
            return (Criteria) this;
        }

        public Criteria andRefDocNoEqualTo(String value) {
            addCriterion("RefDocNo =", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoNotEqualTo(String value) {
            addCriterion("RefDocNo <>", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoGreaterThan(String value) {
            addCriterion("RefDocNo >", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoGreaterThanOrEqualTo(String value) {
            addCriterion("RefDocNo >=", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoLessThan(String value) {
            addCriterion("RefDocNo <", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoLessThanOrEqualTo(String value) {
            addCriterion("RefDocNo <=", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoLike(String value) {
            addCriterion("RefDocNo like", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoNotLike(String value) {
            addCriterion("RefDocNo not like", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoIn(List<String> values) {
            addCriterion("RefDocNo in", values, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoNotIn(List<String> values) {
            addCriterion("RefDocNo not in", values, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoBetween(String value1, String value2) {
            addCriterion("RefDocNo between", value1, value2, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoNotBetween(String value1, String value2) {
            addCriterion("RefDocNo not between", value1, value2, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andPlantIsNull() {
            addCriterion("Plant is null");
            return (Criteria) this;
        }

        public Criteria andPlantIsNotNull() {
            addCriterion("Plant is not null");
            return (Criteria) this;
        }

        public Criteria andPlantEqualTo(String value) {
            addCriterion("Plant =", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotEqualTo(String value) {
            addCriterion("Plant <>", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantGreaterThan(String value) {
            addCriterion("Plant >", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantGreaterThanOrEqualTo(String value) {
            addCriterion("Plant >=", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLessThan(String value) {
            addCriterion("Plant <", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLessThanOrEqualTo(String value) {
            addCriterion("Plant <=", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLike(String value) {
            addCriterion("Plant like", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotLike(String value) {
            addCriterion("Plant not like", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantIn(List<String> values) {
            addCriterion("Plant in", values, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotIn(List<String> values) {
            addCriterion("Plant not in", values, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantBetween(String value1, String value2) {
            addCriterion("Plant between", value1, value2, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotBetween(String value1, String value2) {
            addCriterion("Plant not between", value1, value2, "plant");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRIsNull() {
            addCriterion("REF_DOC_YR is null");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRIsNotNull() {
            addCriterion("REF_DOC_YR is not null");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YREqualTo(String value) {
            addCriterion("REF_DOC_YR =", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRNotEqualTo(String value) {
            addCriterion("REF_DOC_YR <>", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRGreaterThan(String value) {
            addCriterion("REF_DOC_YR >", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRGreaterThanOrEqualTo(String value) {
            addCriterion("REF_DOC_YR >=", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRLessThan(String value) {
            addCriterion("REF_DOC_YR <", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRLessThanOrEqualTo(String value) {
            addCriterion("REF_DOC_YR <=", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRLike(String value) {
            addCriterion("REF_DOC_YR like", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRNotLike(String value) {
            addCriterion("REF_DOC_YR not like", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRIn(List<String> values) {
            addCriterion("REF_DOC_YR in", values, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRNotIn(List<String> values) {
            addCriterion("REF_DOC_YR not in", values, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRBetween(String value1, String value2) {
            addCriterion("REF_DOC_YR between", value1, value2, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRNotBetween(String value1, String value2) {
            addCriterion("REF_DOC_YR not between", value1, value2, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("Status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("Status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("Status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("Status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("Status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("Status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("Status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("Status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("Status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("Status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("Status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("Status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIsNull() {
            addCriterion("OperationType is null");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIsNotNull() {
            addCriterion("OperationType is not null");
            return (Criteria) this;
        }

        public Criteria andOperationTypeEqualTo(String value) {
            addCriterion("OperationType =", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotEqualTo(String value) {
            addCriterion("OperationType <>", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeGreaterThan(String value) {
            addCriterion("OperationType >", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("OperationType >=", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeLessThan(String value) {
            addCriterion("OperationType <", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeLessThanOrEqualTo(String value) {
            addCriterion("OperationType <=", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeLike(String value) {
            addCriterion("OperationType like", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotLike(String value) {
            addCriterion("OperationType not like", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIn(List<String> values) {
            addCriterion("OperationType in", values, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotIn(List<String> values) {
            addCriterion("OperationType not in", values, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeBetween(String value1, String value2) {
            addCriterion("OperationType between", value1, value2, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotBetween(String value1, String value2) {
            addCriterion("OperationType not between", value1, value2, "operationType");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453IsNull() {
            addCriterion("RefDocNo_453 is null");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453IsNotNull() {
            addCriterion("RefDocNo_453 is not null");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453EqualTo(String value) {
            addCriterion("RefDocNo_453 =", value, "refDocNo_453");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453NotEqualTo(String value) {
            addCriterion("RefDocNo_453 <>", value, "refDocNo_453");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453GreaterThan(String value) {
            addCriterion("RefDocNo_453 >", value, "refDocNo_453");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453GreaterThanOrEqualTo(String value) {
            addCriterion("RefDocNo_453 >=", value, "refDocNo_453");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453LessThan(String value) {
            addCriterion("RefDocNo_453 <", value, "refDocNo_453");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453LessThanOrEqualTo(String value) {
            addCriterion("RefDocNo_453 <=", value, "refDocNo_453");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453Like(String value) {
            addCriterion("RefDocNo_453 like", value, "refDocNo_453");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453NotLike(String value) {
            addCriterion("RefDocNo_453 not like", value, "refDocNo_453");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453In(List<String> values) {
            addCriterion("RefDocNo_453 in", values, "refDocNo_453");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453NotIn(List<String> values) {
            addCriterion("RefDocNo_453 not in", values, "refDocNo_453");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453Between(String value1, String value2) {
            addCriterion("RefDocNo_453 between", value1, value2, "refDocNo_453");
            return (Criteria) this;
        }

        public Criteria andRefDocNo_453NotBetween(String value1, String value2) {
            addCriterion("RefDocNo_453 not between", value1, value2, "refDocNo_453");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIsNull() {
            addCriterion("WorkOrder is null");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIsNotNull() {
            addCriterion("WorkOrder is not null");
            return (Criteria) this;
        }

        public Criteria andWorkOrderEqualTo(String value) {
            addCriterion("WorkOrder =", value, "workOrder");
            return (Criteria) this;
        }

        public Criteria andWorkOrderNotEqualTo(String value) {
            addCriterion("WorkOrder <>", value, "workOrder");
            return (Criteria) this;
        }

        public Criteria andWorkOrderGreaterThan(String value) {
            addCriterion("WorkOrder >", value, "workOrder");
            return (Criteria) this;
        }

        public Criteria andWorkOrderGreaterThanOrEqualTo(String value) {
            addCriterion("WorkOrder >=", value, "workOrder");
            return (Criteria) this;
        }

        public Criteria andWorkOrderLessThan(String value) {
            addCriterion("WorkOrder <", value, "workOrder");
            return (Criteria) this;
        }

        public Criteria andWorkOrderLessThanOrEqualTo(String value) {
            addCriterion("WorkOrder <=", value, "workOrder");
            return (Criteria) this;
        }

        public Criteria andWorkOrderLike(String value) {
            addCriterion("WorkOrder like", value, "workOrder");
            return (Criteria) this;
        }

        public Criteria andWorkOrderNotLike(String value) {
            addCriterion("WorkOrder not like", value, "workOrder");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIn(List<String> values) {
            addCriterion("WorkOrder in", values, "workOrder");
            return (Criteria) this;
        }

        public Criteria andWorkOrderNotIn(List<String> values) {
            addCriterion("WorkOrder not in", values, "workOrder");
            return (Criteria) this;
        }

        public Criteria andWorkOrderBetween(String value1, String value2) {
            addCriterion("WorkOrder between", value1, value2, "workOrder");
            return (Criteria) this;
        }

        public Criteria andWorkOrderNotBetween(String value1, String value2) {
            addCriterion("WorkOrder not between", value1, value2, "workOrder");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTIsNull() {
            addCriterion("ITEM_TEXT is null");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTIsNotNull() {
            addCriterion("ITEM_TEXT is not null");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTEqualTo(String value) {
            addCriterion("ITEM_TEXT =", value, "ITEM_TEXT");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTNotEqualTo(String value) {
            addCriterion("ITEM_TEXT <>", value, "ITEM_TEXT");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTGreaterThan(String value) {
            addCriterion("ITEM_TEXT >", value, "ITEM_TEXT");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTGreaterThanOrEqualTo(String value) {
            addCriterion("ITEM_TEXT >=", value, "ITEM_TEXT");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTLessThan(String value) {
            addCriterion("ITEM_TEXT <", value, "ITEM_TEXT");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTLessThanOrEqualTo(String value) {
            addCriterion("ITEM_TEXT <=", value, "ITEM_TEXT");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTLike(String value) {
            addCriterion("ITEM_TEXT like", value, "ITEM_TEXT");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTNotLike(String value) {
            addCriterion("ITEM_TEXT not like", value, "ITEM_TEXT");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTIn(List<String> values) {
            addCriterion("ITEM_TEXT in", values, "ITEM_TEXT");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTNotIn(List<String> values) {
            addCriterion("ITEM_TEXT not in", values, "ITEM_TEXT");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTBetween(String value1, String value2) {
            addCriterion("ITEM_TEXT between", value1, value2, "ITEM_TEXT");
            return (Criteria) this;
        }

        public Criteria andITEM_TEXTNotBetween(String value1, String value2) {
            addCriterion("ITEM_TEXT not between", value1, value2, "ITEM_TEXT");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTIsNull() {
            addCriterion("UNLOAD_PT is null");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTIsNotNull() {
            addCriterion("UNLOAD_PT is not null");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTEqualTo(String value) {
            addCriterion("UNLOAD_PT =", value, "UNLOAD_PT");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTNotEqualTo(String value) {
            addCriterion("UNLOAD_PT <>", value, "UNLOAD_PT");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTGreaterThan(String value) {
            addCriterion("UNLOAD_PT >", value, "UNLOAD_PT");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTGreaterThanOrEqualTo(String value) {
            addCriterion("UNLOAD_PT >=", value, "UNLOAD_PT");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTLessThan(String value) {
            addCriterion("UNLOAD_PT <", value, "UNLOAD_PT");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTLessThanOrEqualTo(String value) {
            addCriterion("UNLOAD_PT <=", value, "UNLOAD_PT");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTLike(String value) {
            addCriterion("UNLOAD_PT like", value, "UNLOAD_PT");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTNotLike(String value) {
            addCriterion("UNLOAD_PT not like", value, "UNLOAD_PT");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTIn(List<String> values) {
            addCriterion("UNLOAD_PT in", values, "UNLOAD_PT");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTNotIn(List<String> values) {
            addCriterion("UNLOAD_PT not in", values, "UNLOAD_PT");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTBetween(String value1, String value2) {
            addCriterion("UNLOAD_PT between", value1, value2, "UNLOAD_PT");
            return (Criteria) this;
        }

        public Criteria andUNLOAD_PTNotBetween(String value1, String value2) {
            addCriterion("UNLOAD_PT not between", value1, value2, "UNLOAD_PT");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMIsNull() {
            addCriterion("MATDOC_ITM is null");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMIsNotNull() {
            addCriterion("MATDOC_ITM is not null");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMEqualTo(String value) {
            addCriterion("MATDOC_ITM =", value, "MATDOC_ITM");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMNotEqualTo(String value) {
            addCriterion("MATDOC_ITM <>", value, "MATDOC_ITM");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMGreaterThan(String value) {
            addCriterion("MATDOC_ITM >", value, "MATDOC_ITM");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMGreaterThanOrEqualTo(String value) {
            addCriterion("MATDOC_ITM >=", value, "MATDOC_ITM");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMLessThan(String value) {
            addCriterion("MATDOC_ITM <", value, "MATDOC_ITM");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMLessThanOrEqualTo(String value) {
            addCriterion("MATDOC_ITM <=", value, "MATDOC_ITM");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMLike(String value) {
            addCriterion("MATDOC_ITM like", value, "MATDOC_ITM");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMNotLike(String value) {
            addCriterion("MATDOC_ITM not like", value, "MATDOC_ITM");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMIn(List<String> values) {
            addCriterion("MATDOC_ITM in", values, "MATDOC_ITM");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMNotIn(List<String> values) {
            addCriterion("MATDOC_ITM not in", values, "MATDOC_ITM");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMBetween(String value1, String value2) {
            addCriterion("MATDOC_ITM between", value1, value2, "MATDOC_ITM");
            return (Criteria) this;
        }

        public Criteria andMATDOC_ITMNotBetween(String value1, String value2) {
            addCriterion("MATDOC_ITM not between", value1, value2, "MATDOC_ITM");
            return (Criteria) this;
        }

        public Criteria andMRN_BYIsNull() {
            addCriterion("MRN_BY is null");
            return (Criteria) this;
        }

        public Criteria andMRN_BYIsNotNull() {
            addCriterion("MRN_BY is not null");
            return (Criteria) this;
        }

        public Criteria andMRN_BYEqualTo(String value) {
            addCriterion("MRN_BY =", value, "MRN_BY");
            return (Criteria) this;
        }

        public Criteria andMRN_BYNotEqualTo(String value) {
            addCriterion("MRN_BY <>", value, "MRN_BY");
            return (Criteria) this;
        }

        public Criteria andMRN_BYGreaterThan(String value) {
            addCriterion("MRN_BY >", value, "MRN_BY");
            return (Criteria) this;
        }

        public Criteria andMRN_BYGreaterThanOrEqualTo(String value) {
            addCriterion("MRN_BY >=", value, "MRN_BY");
            return (Criteria) this;
        }

        public Criteria andMRN_BYLessThan(String value) {
            addCriterion("MRN_BY <", value, "MRN_BY");
            return (Criteria) this;
        }

        public Criteria andMRN_BYLessThanOrEqualTo(String value) {
            addCriterion("MRN_BY <=", value, "MRN_BY");
            return (Criteria) this;
        }

        public Criteria andMRN_BYLike(String value) {
            addCriterion("MRN_BY like", value, "MRN_BY");
            return (Criteria) this;
        }

        public Criteria andMRN_BYNotLike(String value) {
            addCriterion("MRN_BY not like", value, "MRN_BY");
            return (Criteria) this;
        }

        public Criteria andMRN_BYIn(List<String> values) {
            addCriterion("MRN_BY in", values, "MRN_BY");
            return (Criteria) this;
        }

        public Criteria andMRN_BYNotIn(List<String> values) {
            addCriterion("MRN_BY not in", values, "MRN_BY");
            return (Criteria) this;
        }

        public Criteria andMRN_BYBetween(String value1, String value2) {
            addCriterion("MRN_BY between", value1, value2, "MRN_BY");
            return (Criteria) this;
        }

        public Criteria andMRN_BYNotBetween(String value1, String value2) {
            addCriterion("MRN_BY not between", value1, value2, "MRN_BY");
            return (Criteria) this;
        }

        public Criteria andIsLockedIsNull() {
            addCriterion("IsLocked is null");
            return (Criteria) this;
        }

        public Criteria andIsLockedIsNotNull() {
            addCriterion("IsLocked is not null");
            return (Criteria) this;
        }

        public Criteria andIsLockedEqualTo(Boolean value) {
            addCriterion("IsLocked =", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedNotEqualTo(Boolean value) {
            addCriterion("IsLocked <>", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedGreaterThan(Boolean value) {
            addCriterion("IsLocked >", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsLocked >=", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedLessThan(Boolean value) {
            addCriterion("IsLocked <", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedLessThanOrEqualTo(Boolean value) {
            addCriterion("IsLocked <=", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedIn(List<Boolean> values) {
            addCriterion("IsLocked in", values, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedNotIn(List<Boolean> values) {
            addCriterion("IsLocked not in", values, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedBetween(Boolean value1, Boolean value2) {
            addCriterion("IsLocked between", value1, value2, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsLocked not between", value1, value2, "isLocked");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 21 13:50:25 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UID_xTend_MaterialTransactionsRHDCDW
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}