package ht.model.model131;

import java.util.Date;

public class UID_xTend_MaterialTransactionsRHDCDW {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionHistoryId
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String transactionHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.UID
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.Batch
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String batch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.PartNumber
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String partNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.Quantity
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private Double quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.UOM
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String UOM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.ResultStatus
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private Integer resultStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.FromStock_Input
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String fromStock_Input;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.FromStock
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String fromStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.FromStock_Bin
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String fromStock_Bin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.ToStock_Input
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String toStock_Input;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.ToStock
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String toStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.ToStock_Bin
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String toStock_Bin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionUser
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String transactionUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionTime
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private Date transactionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionUser_1
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String transactionUser_1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionTime_1
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private Date transactionTime_1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionType
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionReason
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String transactionReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.RFCTemplateID
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String RFCTemplateID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.RefDocNo
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String refDocNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.Plant
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String plant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.REF_DOC_YR
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String REF_DOC_YR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.Status
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.OperationType
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.RefDocNo_453
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String refDocNo_453;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.WorkOrder
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String workOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.ITEM_TEXT
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String ITEM_TEXT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.UNLOAD_PT
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String UNLOAD_PT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.MATDOC_ITM
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String MATDOC_ITM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.MRN_BY
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String MRN_BY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.IsLocked
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private Boolean isLocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UID_xTend_MaterialTransactionsRHDCDW.MESSAGE
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    private String MESSAGE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionHistoryId
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.TransactionHistoryId
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getTransactionHistoryId() {
        return transactionHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionHistoryId
     *
     * @param transactionHistoryId the value for UID_xTend_MaterialTransactionsRHDCDW.TransactionHistoryId
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setTransactionHistoryId(String transactionHistoryId) {
        this.transactionHistoryId = transactionHistoryId == null ? null : transactionHistoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.UID
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.UID
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.UID
     *
     * @param UID the value for UID_xTend_MaterialTransactionsRHDCDW.UID
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setUID(String UID) {
        this.UID = UID == null ? null : UID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.Batch
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.Batch
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.Batch
     *
     * @param batch the value for UID_xTend_MaterialTransactionsRHDCDW.Batch
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setBatch(String batch) {
        this.batch = batch == null ? null : batch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.PartNumber
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.PartNumber
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getPartNumber() {
        return partNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.PartNumber
     *
     * @param partNumber the value for UID_xTend_MaterialTransactionsRHDCDW.PartNumber
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber == null ? null : partNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.Quantity
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.Quantity
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public Double getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.Quantity
     *
     * @param quantity the value for UID_xTend_MaterialTransactionsRHDCDW.Quantity
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.UOM
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.UOM
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getUOM() {
        return UOM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.UOM
     *
     * @param UOM the value for UID_xTend_MaterialTransactionsRHDCDW.UOM
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setUOM(String UOM) {
        this.UOM = UOM == null ? null : UOM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.ResultStatus
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.ResultStatus
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public Integer getResultStatus() {
        return resultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.ResultStatus
     *
     * @param resultStatus the value for UID_xTend_MaterialTransactionsRHDCDW.ResultStatus
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setResultStatus(Integer resultStatus) {
        this.resultStatus = resultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.FromStock_Input
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.FromStock_Input
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getFromStock_Input() {
        return fromStock_Input;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.FromStock_Input
     *
     * @param fromStock_Input the value for UID_xTend_MaterialTransactionsRHDCDW.FromStock_Input
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setFromStock_Input(String fromStock_Input) {
        this.fromStock_Input = fromStock_Input == null ? null : fromStock_Input.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.FromStock
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.FromStock
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getFromStock() {
        return fromStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.FromStock
     *
     * @param fromStock the value for UID_xTend_MaterialTransactionsRHDCDW.FromStock
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setFromStock(String fromStock) {
        this.fromStock = fromStock == null ? null : fromStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.FromStock_Bin
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.FromStock_Bin
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getFromStock_Bin() {
        return fromStock_Bin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.FromStock_Bin
     *
     * @param fromStock_Bin the value for UID_xTend_MaterialTransactionsRHDCDW.FromStock_Bin
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setFromStock_Bin(String fromStock_Bin) {
        this.fromStock_Bin = fromStock_Bin == null ? null : fromStock_Bin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.ToStock_Input
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.ToStock_Input
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getToStock_Input() {
        return toStock_Input;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.ToStock_Input
     *
     * @param toStock_Input the value for UID_xTend_MaterialTransactionsRHDCDW.ToStock_Input
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setToStock_Input(String toStock_Input) {
        this.toStock_Input = toStock_Input == null ? null : toStock_Input.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.ToStock
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.ToStock
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getToStock() {
        return toStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.ToStock
     *
     * @param toStock the value for UID_xTend_MaterialTransactionsRHDCDW.ToStock
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setToStock(String toStock) {
        this.toStock = toStock == null ? null : toStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.ToStock_Bin
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.ToStock_Bin
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getToStock_Bin() {
        return toStock_Bin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.ToStock_Bin
     *
     * @param toStock_Bin the value for UID_xTend_MaterialTransactionsRHDCDW.ToStock_Bin
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setToStock_Bin(String toStock_Bin) {
        this.toStock_Bin = toStock_Bin == null ? null : toStock_Bin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionUser
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.TransactionUser
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getTransactionUser() {
        return transactionUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionUser
     *
     * @param transactionUser the value for UID_xTend_MaterialTransactionsRHDCDW.TransactionUser
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setTransactionUser(String transactionUser) {
        this.transactionUser = transactionUser == null ? null : transactionUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionTime
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.TransactionTime
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public Date getTransactionTime() {
        return transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionTime
     *
     * @param transactionTime the value for UID_xTend_MaterialTransactionsRHDCDW.TransactionTime
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setTransactionTime(Date transactionTime) {
        this.transactionTime = transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionUser_1
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.TransactionUser_1
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getTransactionUser_1() {
        return transactionUser_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionUser_1
     *
     * @param transactionUser_1 the value for UID_xTend_MaterialTransactionsRHDCDW.TransactionUser_1
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setTransactionUser_1(String transactionUser_1) {
        this.transactionUser_1 = transactionUser_1 == null ? null : transactionUser_1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionTime_1
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.TransactionTime_1
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public Date getTransactionTime_1() {
        return transactionTime_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionTime_1
     *
     * @param transactionTime_1 the value for UID_xTend_MaterialTransactionsRHDCDW.TransactionTime_1
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setTransactionTime_1(Date transactionTime_1) {
        this.transactionTime_1 = transactionTime_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionType
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.TransactionType
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionType
     *
     * @param transactionType the value for UID_xTend_MaterialTransactionsRHDCDW.TransactionType
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType == null ? null : transactionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionReason
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.TransactionReason
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getTransactionReason() {
        return transactionReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.TransactionReason
     *
     * @param transactionReason the value for UID_xTend_MaterialTransactionsRHDCDW.TransactionReason
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setTransactionReason(String transactionReason) {
        this.transactionReason = transactionReason == null ? null : transactionReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.RFCTemplateID
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.RFCTemplateID
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getRFCTemplateID() {
        return RFCTemplateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.RFCTemplateID
     *
     * @param RFCTemplateID the value for UID_xTend_MaterialTransactionsRHDCDW.RFCTemplateID
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setRFCTemplateID(String RFCTemplateID) {
        this.RFCTemplateID = RFCTemplateID == null ? null : RFCTemplateID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.RefDocNo
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.RefDocNo
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getRefDocNo() {
        return refDocNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.RefDocNo
     *
     * @param refDocNo the value for UID_xTend_MaterialTransactionsRHDCDW.RefDocNo
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setRefDocNo(String refDocNo) {
        this.refDocNo = refDocNo == null ? null : refDocNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.Plant
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.Plant
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getPlant() {
        return plant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.Plant
     *
     * @param plant the value for UID_xTend_MaterialTransactionsRHDCDW.Plant
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setPlant(String plant) {
        this.plant = plant == null ? null : plant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.REF_DOC_YR
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.REF_DOC_YR
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getREF_DOC_YR() {
        return REF_DOC_YR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.REF_DOC_YR
     *
     * @param REF_DOC_YR the value for UID_xTend_MaterialTransactionsRHDCDW.REF_DOC_YR
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setREF_DOC_YR(String REF_DOC_YR) {
        this.REF_DOC_YR = REF_DOC_YR == null ? null : REF_DOC_YR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.Status
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.Status
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.Status
     *
     * @param status the value for UID_xTend_MaterialTransactionsRHDCDW.Status
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.OperationType
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.OperationType
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.OperationType
     *
     * @param operationType the value for UID_xTend_MaterialTransactionsRHDCDW.OperationType
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.RefDocNo_453
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.RefDocNo_453
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getRefDocNo_453() {
        return refDocNo_453;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.RefDocNo_453
     *
     * @param refDocNo_453 the value for UID_xTend_MaterialTransactionsRHDCDW.RefDocNo_453
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setRefDocNo_453(String refDocNo_453) {
        this.refDocNo_453 = refDocNo_453 == null ? null : refDocNo_453.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.WorkOrder
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.WorkOrder
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getWorkOrder() {
        return workOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.WorkOrder
     *
     * @param workOrder the value for UID_xTend_MaterialTransactionsRHDCDW.WorkOrder
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setWorkOrder(String workOrder) {
        this.workOrder = workOrder == null ? null : workOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.ITEM_TEXT
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.ITEM_TEXT
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getITEM_TEXT() {
        return ITEM_TEXT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.ITEM_TEXT
     *
     * @param ITEM_TEXT the value for UID_xTend_MaterialTransactionsRHDCDW.ITEM_TEXT
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setITEM_TEXT(String ITEM_TEXT) {
        this.ITEM_TEXT = ITEM_TEXT == null ? null : ITEM_TEXT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.UNLOAD_PT
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.UNLOAD_PT
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getUNLOAD_PT() {
        return UNLOAD_PT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.UNLOAD_PT
     *
     * @param UNLOAD_PT the value for UID_xTend_MaterialTransactionsRHDCDW.UNLOAD_PT
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setUNLOAD_PT(String UNLOAD_PT) {
        this.UNLOAD_PT = UNLOAD_PT == null ? null : UNLOAD_PT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.MATDOC_ITM
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.MATDOC_ITM
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getMATDOC_ITM() {
        return MATDOC_ITM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.MATDOC_ITM
     *
     * @param MATDOC_ITM the value for UID_xTend_MaterialTransactionsRHDCDW.MATDOC_ITM
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setMATDOC_ITM(String MATDOC_ITM) {
        this.MATDOC_ITM = MATDOC_ITM == null ? null : MATDOC_ITM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.MRN_BY
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.MRN_BY
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getMRN_BY() {
        return MRN_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.MRN_BY
     *
     * @param MRN_BY the value for UID_xTend_MaterialTransactionsRHDCDW.MRN_BY
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setMRN_BY(String MRN_BY) {
        this.MRN_BY = MRN_BY == null ? null : MRN_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.IsLocked
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.IsLocked
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public Boolean getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.IsLocked
     *
     * @param isLocked the value for UID_xTend_MaterialTransactionsRHDCDW.IsLocked
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setIsLocked(Boolean isLocked) {
        this.isLocked = isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UID_xTend_MaterialTransactionsRHDCDW.MESSAGE
     *
     * @return the value of UID_xTend_MaterialTransactionsRHDCDW.MESSAGE
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public String getMESSAGE() {
        return MESSAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UID_xTend_MaterialTransactionsRHDCDW.MESSAGE
     *
     * @param MESSAGE the value for UID_xTend_MaterialTransactionsRHDCDW.MESSAGE
     *
     * @mbggenerated Mon Nov 21 13:50:25 CST 2022
     */
    public void setMESSAGE(String MESSAGE) {
        this.MESSAGE = MESSAGE == null ? null : MESSAGE.trim();
    }
}