package ht.mappergenerator.mapper33;

import ht.model.model33.ToReceiveWarehouseB;
import ht.model.model33.ToReceiveWarehouseBExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ToReceiveWarehouseBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ToReceiveWarehouseB
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    int countByExample(ToReceiveWarehouseBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ToReceiveWarehouseB
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    int deleteByExample(ToReceiveWarehouseBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ToReceiveWarehouseB
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ToReceiveWarehouseB
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    int insert(ToReceiveWarehouseB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ToReceiveWarehouseB
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    int insertSelective(ToReceiveWarehouseB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ToReceiveWarehouseB
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    List<ToReceiveWarehouseB> selectByExample(ToReceiveWarehouseBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ToReceiveWarehouseB
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    ToReceiveWarehouseB selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ToReceiveWarehouseB
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    int updateByExampleSelective(@Param("record") ToReceiveWarehouseB record, @Param("example") ToReceiveWarehouseBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ToReceiveWarehouseB
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    int updateByExample(@Param("record") ToReceiveWarehouseB record, @Param("example") ToReceiveWarehouseBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ToReceiveWarehouseB
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    int updateByPrimaryKeySelective(ToReceiveWarehouseB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ToReceiveWarehouseB
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    int updateByPrimaryKey(ToReceiveWarehouseB record);
}