package ht.model.model26;

import java.math.BigDecimal;
import java.util.Date;

public class Vendorrid {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.id
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.customerCode
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String customerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.plent
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String plent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.supplierCode
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.supplierName
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.partNumber
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String partNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.partdesc
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String partdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.lt
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String lt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.manufPartNumber
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String manufPartNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.manufactoryName
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String manufactoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.customerPartNumber
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String customerPartNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.po
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String po;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.poItem
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String poItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.poIssueDate
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String poIssueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.poOrderedQTY
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String poOrderedQTY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.poOutQTY
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String poOutQTY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.unit
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.updateDate
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.printQTY
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private BigDecimal printQTY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.vendorcode
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String vendorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.rid
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.lastestETA
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String lastestETA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.newETA
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String newETA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.minbm
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String minbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.createuser
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.createdate
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.ln
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String ln;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.coo
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String coo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.cid
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.productiondate
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String productiondate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.poETA
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String poETA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.productiondate2
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String productiondate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.drid
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String drid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.date2Type
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String date2Type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.edi_id
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private Long edi_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.Schedul
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String schedul;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.GRN
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String GRN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.UpAegis
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String upAegis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.GRN103
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String GRN103;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.E_MJAHR
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String e_MJAHR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.NOTES
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String NOTES;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.E_CHARG
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String e_CHARG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.E_PRUEFLOS
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String e_PRUEFLOS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.E_CHARG103
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String e_CHARG103;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.GRNDATE
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private Date GRNDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.GEN103DATE
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private Date GEN103DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.UpAegisDATE
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private Date upAegisDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.WEIGHT
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String WEIGHT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.BOXNO
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String BOXNO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.MSD
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String MSD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.VendorPN
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String vendorPN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.FreeQTY
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String freeQTY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.Version
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.UMREN
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private Integer UMREN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.UMREZ
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private Integer UMREZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.Mvt
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String mvt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.MvtReason
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String mvtReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.MvtK
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String mvtK;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.EKNAM
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String EKNAM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.SMTP_ADDR
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String SMTP_ADDR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.TEL_NUMBER
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String TEL_NUMBER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.ZUIDVAL
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String ZUIDVAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.PoUnit
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String poUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.ISbatch
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String ISbatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.StockName1
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String stockName1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.StockName2
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String stockName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.EFNO
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String EFNO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.PATH
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String PATH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.STGE_LOC
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String STGE_LOC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.xqty
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private Integer xqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.UpHTMES
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private String upHTMES;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendorrid.UpHTMESDATE
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    private Date upHTMESDATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.id
     *
     * @return the value of vendorrid.id
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.id
     *
     * @param id the value for vendorrid.id
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.customerCode
     *
     * @return the value of vendorrid.customerCode
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.customerCode
     *
     * @param customerCode the value for vendorrid.customerCode
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode == null ? null : customerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.plent
     *
     * @return the value of vendorrid.plent
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getPlent() {
        return plent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.plent
     *
     * @param plent the value for vendorrid.plent
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setPlent(String plent) {
        this.plent = plent == null ? null : plent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.supplierCode
     *
     * @return the value of vendorrid.supplierCode
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.supplierCode
     *
     * @param supplierCode the value for vendorrid.supplierCode
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.supplierName
     *
     * @return the value of vendorrid.supplierName
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.supplierName
     *
     * @param supplierName the value for vendorrid.supplierName
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.partNumber
     *
     * @return the value of vendorrid.partNumber
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getPartNumber() {
        return partNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.partNumber
     *
     * @param partNumber the value for vendorrid.partNumber
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber == null ? null : partNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.partdesc
     *
     * @return the value of vendorrid.partdesc
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getPartdesc() {
        return partdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.partdesc
     *
     * @param partdesc the value for vendorrid.partdesc
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setPartdesc(String partdesc) {
        this.partdesc = partdesc == null ? null : partdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.lt
     *
     * @return the value of vendorrid.lt
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getLt() {
        return lt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.lt
     *
     * @param lt the value for vendorrid.lt
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setLt(String lt) {
        this.lt = lt == null ? null : lt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.manufPartNumber
     *
     * @return the value of vendorrid.manufPartNumber
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getManufPartNumber() {
        return manufPartNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.manufPartNumber
     *
     * @param manufPartNumber the value for vendorrid.manufPartNumber
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setManufPartNumber(String manufPartNumber) {
        this.manufPartNumber = manufPartNumber == null ? null : manufPartNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.manufactoryName
     *
     * @return the value of vendorrid.manufactoryName
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getManufactoryName() {
        return manufactoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.manufactoryName
     *
     * @param manufactoryName the value for vendorrid.manufactoryName
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setManufactoryName(String manufactoryName) {
        this.manufactoryName = manufactoryName == null ? null : manufactoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.customerPartNumber
     *
     * @return the value of vendorrid.customerPartNumber
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getCustomerPartNumber() {
        return customerPartNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.customerPartNumber
     *
     * @param customerPartNumber the value for vendorrid.customerPartNumber
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setCustomerPartNumber(String customerPartNumber) {
        this.customerPartNumber = customerPartNumber == null ? null : customerPartNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.po
     *
     * @return the value of vendorrid.po
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getPo() {
        return po;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.po
     *
     * @param po the value for vendorrid.po
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setPo(String po) {
        this.po = po == null ? null : po.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.poItem
     *
     * @return the value of vendorrid.poItem
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getPoItem() {
        return poItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.poItem
     *
     * @param poItem the value for vendorrid.poItem
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setPoItem(String poItem) {
        this.poItem = poItem == null ? null : poItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.poIssueDate
     *
     * @return the value of vendorrid.poIssueDate
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getPoIssueDate() {
        return poIssueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.poIssueDate
     *
     * @param poIssueDate the value for vendorrid.poIssueDate
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setPoIssueDate(String poIssueDate) {
        this.poIssueDate = poIssueDate == null ? null : poIssueDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.poOrderedQTY
     *
     * @return the value of vendorrid.poOrderedQTY
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getPoOrderedQTY() {
        return poOrderedQTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.poOrderedQTY
     *
     * @param poOrderedQTY the value for vendorrid.poOrderedQTY
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setPoOrderedQTY(String poOrderedQTY) {
        this.poOrderedQTY = poOrderedQTY == null ? null : poOrderedQTY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.poOutQTY
     *
     * @return the value of vendorrid.poOutQTY
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getPoOutQTY() {
        return poOutQTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.poOutQTY
     *
     * @param poOutQTY the value for vendorrid.poOutQTY
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setPoOutQTY(String poOutQTY) {
        this.poOutQTY = poOutQTY == null ? null : poOutQTY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.unit
     *
     * @return the value of vendorrid.unit
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.unit
     *
     * @param unit the value for vendorrid.unit
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.updateDate
     *
     * @return the value of vendorrid.updateDate
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.updateDate
     *
     * @param updateDate the value for vendorrid.updateDate
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.printQTY
     *
     * @return the value of vendorrid.printQTY
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public BigDecimal getPrintQTY() {
        return printQTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.printQTY
     *
     * @param printQTY the value for vendorrid.printQTY
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setPrintQTY(BigDecimal printQTY) {
        this.printQTY = printQTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.vendorcode
     *
     * @return the value of vendorrid.vendorcode
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getVendorcode() {
        return vendorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.vendorcode
     *
     * @param vendorcode the value for vendorrid.vendorcode
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setVendorcode(String vendorcode) {
        this.vendorcode = vendorcode == null ? null : vendorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.rid
     *
     * @return the value of vendorrid.rid
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.rid
     *
     * @param rid the value for vendorrid.rid
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setRid(String rid) {
        this.rid = rid == null ? null : rid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.lastestETA
     *
     * @return the value of vendorrid.lastestETA
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getLastestETA() {
        return lastestETA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.lastestETA
     *
     * @param lastestETA the value for vendorrid.lastestETA
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setLastestETA(String lastestETA) {
        this.lastestETA = lastestETA == null ? null : lastestETA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.newETA
     *
     * @return the value of vendorrid.newETA
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getNewETA() {
        return newETA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.newETA
     *
     * @param newETA the value for vendorrid.newETA
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setNewETA(String newETA) {
        this.newETA = newETA == null ? null : newETA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.minbm
     *
     * @return the value of vendorrid.minbm
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getMinbm() {
        return minbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.minbm
     *
     * @param minbm the value for vendorrid.minbm
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setMinbm(String minbm) {
        this.minbm = minbm == null ? null : minbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.createuser
     *
     * @return the value of vendorrid.createuser
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.createuser
     *
     * @param createuser the value for vendorrid.createuser
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.createdate
     *
     * @return the value of vendorrid.createdate
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.createdate
     *
     * @param createdate the value for vendorrid.createdate
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.ln
     *
     * @return the value of vendorrid.ln
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getLn() {
        return ln;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.ln
     *
     * @param ln the value for vendorrid.ln
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setLn(String ln) {
        this.ln = ln == null ? null : ln.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.coo
     *
     * @return the value of vendorrid.coo
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getCoo() {
        return coo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.coo
     *
     * @param coo the value for vendorrid.coo
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setCoo(String coo) {
        this.coo = coo == null ? null : coo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.cid
     *
     * @return the value of vendorrid.cid
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.cid
     *
     * @param cid the value for vendorrid.cid
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.productiondate
     *
     * @return the value of vendorrid.productiondate
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getProductiondate() {
        return productiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.productiondate
     *
     * @param productiondate the value for vendorrid.productiondate
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setProductiondate(String productiondate) {
        this.productiondate = productiondate == null ? null : productiondate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.poETA
     *
     * @return the value of vendorrid.poETA
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getPoETA() {
        return poETA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.poETA
     *
     * @param poETA the value for vendorrid.poETA
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setPoETA(String poETA) {
        this.poETA = poETA == null ? null : poETA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.productiondate2
     *
     * @return the value of vendorrid.productiondate2
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getProductiondate2() {
        return productiondate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.productiondate2
     *
     * @param productiondate2 the value for vendorrid.productiondate2
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setProductiondate2(String productiondate2) {
        this.productiondate2 = productiondate2 == null ? null : productiondate2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.drid
     *
     * @return the value of vendorrid.drid
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getDrid() {
        return drid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.drid
     *
     * @param drid the value for vendorrid.drid
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setDrid(String drid) {
        this.drid = drid == null ? null : drid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.date2Type
     *
     * @return the value of vendorrid.date2Type
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getDate2Type() {
        return date2Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.date2Type
     *
     * @param date2Type the value for vendorrid.date2Type
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setDate2Type(String date2Type) {
        this.date2Type = date2Type == null ? null : date2Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.edi_id
     *
     * @return the value of vendorrid.edi_id
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public Long getEdi_id() {
        return edi_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.edi_id
     *
     * @param edi_id the value for vendorrid.edi_id
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setEdi_id(Long edi_id) {
        this.edi_id = edi_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.Schedul
     *
     * @return the value of vendorrid.Schedul
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getSchedul() {
        return schedul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.Schedul
     *
     * @param schedul the value for vendorrid.Schedul
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setSchedul(String schedul) {
        this.schedul = schedul == null ? null : schedul.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.GRN
     *
     * @return the value of vendorrid.GRN
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getGRN() {
        return GRN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.GRN
     *
     * @param GRN the value for vendorrid.GRN
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setGRN(String GRN) {
        this.GRN = GRN == null ? null : GRN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.UpAegis
     *
     * @return the value of vendorrid.UpAegis
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getUpAegis() {
        return upAegis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.UpAegis
     *
     * @param upAegis the value for vendorrid.UpAegis
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setUpAegis(String upAegis) {
        this.upAegis = upAegis == null ? null : upAegis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.GRN103
     *
     * @return the value of vendorrid.GRN103
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getGRN103() {
        return GRN103;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.GRN103
     *
     * @param GRN103 the value for vendorrid.GRN103
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setGRN103(String GRN103) {
        this.GRN103 = GRN103 == null ? null : GRN103.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.E_MJAHR
     *
     * @return the value of vendorrid.E_MJAHR
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getE_MJAHR() {
        return e_MJAHR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.E_MJAHR
     *
     * @param e_MJAHR the value for vendorrid.E_MJAHR
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setE_MJAHR(String e_MJAHR) {
        this.e_MJAHR = e_MJAHR == null ? null : e_MJAHR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.NOTES
     *
     * @return the value of vendorrid.NOTES
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getNOTES() {
        return NOTES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.NOTES
     *
     * @param NOTES the value for vendorrid.NOTES
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setNOTES(String NOTES) {
        this.NOTES = NOTES == null ? null : NOTES.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.E_CHARG
     *
     * @return the value of vendorrid.E_CHARG
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getE_CHARG() {
        return e_CHARG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.E_CHARG
     *
     * @param e_CHARG the value for vendorrid.E_CHARG
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setE_CHARG(String e_CHARG) {
        this.e_CHARG = e_CHARG == null ? null : e_CHARG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.E_PRUEFLOS
     *
     * @return the value of vendorrid.E_PRUEFLOS
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getE_PRUEFLOS() {
        return e_PRUEFLOS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.E_PRUEFLOS
     *
     * @param e_PRUEFLOS the value for vendorrid.E_PRUEFLOS
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setE_PRUEFLOS(String e_PRUEFLOS) {
        this.e_PRUEFLOS = e_PRUEFLOS == null ? null : e_PRUEFLOS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.E_CHARG103
     *
     * @return the value of vendorrid.E_CHARG103
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getE_CHARG103() {
        return e_CHARG103;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.E_CHARG103
     *
     * @param e_CHARG103 the value for vendorrid.E_CHARG103
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setE_CHARG103(String e_CHARG103) {
        this.e_CHARG103 = e_CHARG103 == null ? null : e_CHARG103.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.GRNDATE
     *
     * @return the value of vendorrid.GRNDATE
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public Date getGRNDATE() {
        return GRNDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.GRNDATE
     *
     * @param GRNDATE the value for vendorrid.GRNDATE
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setGRNDATE(Date GRNDATE) {
        this.GRNDATE = GRNDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.GEN103DATE
     *
     * @return the value of vendorrid.GEN103DATE
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public Date getGEN103DATE() {
        return GEN103DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.GEN103DATE
     *
     * @param GEN103DATE the value for vendorrid.GEN103DATE
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setGEN103DATE(Date GEN103DATE) {
        this.GEN103DATE = GEN103DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.UpAegisDATE
     *
     * @return the value of vendorrid.UpAegisDATE
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public Date getUpAegisDATE() {
        return upAegisDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.UpAegisDATE
     *
     * @param upAegisDATE the value for vendorrid.UpAegisDATE
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setUpAegisDATE(Date upAegisDATE) {
        this.upAegisDATE = upAegisDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.WEIGHT
     *
     * @return the value of vendorrid.WEIGHT
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getWEIGHT() {
        return WEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.WEIGHT
     *
     * @param WEIGHT the value for vendorrid.WEIGHT
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setWEIGHT(String WEIGHT) {
        this.WEIGHT = WEIGHT == null ? null : WEIGHT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.BOXNO
     *
     * @return the value of vendorrid.BOXNO
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getBOXNO() {
        return BOXNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.BOXNO
     *
     * @param BOXNO the value for vendorrid.BOXNO
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setBOXNO(String BOXNO) {
        this.BOXNO = BOXNO == null ? null : BOXNO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.MSD
     *
     * @return the value of vendorrid.MSD
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getMSD() {
        return MSD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.MSD
     *
     * @param MSD the value for vendorrid.MSD
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setMSD(String MSD) {
        this.MSD = MSD == null ? null : MSD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.VendorPN
     *
     * @return the value of vendorrid.VendorPN
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getVendorPN() {
        return vendorPN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.VendorPN
     *
     * @param vendorPN the value for vendorrid.VendorPN
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setVendorPN(String vendorPN) {
        this.vendorPN = vendorPN == null ? null : vendorPN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.FreeQTY
     *
     * @return the value of vendorrid.FreeQTY
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getFreeQTY() {
        return freeQTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.FreeQTY
     *
     * @param freeQTY the value for vendorrid.FreeQTY
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setFreeQTY(String freeQTY) {
        this.freeQTY = freeQTY == null ? null : freeQTY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.Version
     *
     * @return the value of vendorrid.Version
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.Version
     *
     * @param version the value for vendorrid.Version
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.UMREN
     *
     * @return the value of vendorrid.UMREN
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public Integer getUMREN() {
        return UMREN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.UMREN
     *
     * @param UMREN the value for vendorrid.UMREN
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setUMREN(Integer UMREN) {
        this.UMREN = UMREN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.UMREZ
     *
     * @return the value of vendorrid.UMREZ
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public Integer getUMREZ() {
        return UMREZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.UMREZ
     *
     * @param UMREZ the value for vendorrid.UMREZ
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setUMREZ(Integer UMREZ) {
        this.UMREZ = UMREZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.Mvt
     *
     * @return the value of vendorrid.Mvt
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getMvt() {
        return mvt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.Mvt
     *
     * @param mvt the value for vendorrid.Mvt
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setMvt(String mvt) {
        this.mvt = mvt == null ? null : mvt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.MvtReason
     *
     * @return the value of vendorrid.MvtReason
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getMvtReason() {
        return mvtReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.MvtReason
     *
     * @param mvtReason the value for vendorrid.MvtReason
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setMvtReason(String mvtReason) {
        this.mvtReason = mvtReason == null ? null : mvtReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.MvtK
     *
     * @return the value of vendorrid.MvtK
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getMvtK() {
        return mvtK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.MvtK
     *
     * @param mvtK the value for vendorrid.MvtK
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setMvtK(String mvtK) {
        this.mvtK = mvtK == null ? null : mvtK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.EKNAM
     *
     * @return the value of vendorrid.EKNAM
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getEKNAM() {
        return EKNAM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.EKNAM
     *
     * @param EKNAM the value for vendorrid.EKNAM
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setEKNAM(String EKNAM) {
        this.EKNAM = EKNAM == null ? null : EKNAM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.SMTP_ADDR
     *
     * @return the value of vendorrid.SMTP_ADDR
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getSMTP_ADDR() {
        return SMTP_ADDR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.SMTP_ADDR
     *
     * @param SMTP_ADDR the value for vendorrid.SMTP_ADDR
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setSMTP_ADDR(String SMTP_ADDR) {
        this.SMTP_ADDR = SMTP_ADDR == null ? null : SMTP_ADDR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.TEL_NUMBER
     *
     * @return the value of vendorrid.TEL_NUMBER
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getTEL_NUMBER() {
        return TEL_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.TEL_NUMBER
     *
     * @param TEL_NUMBER the value for vendorrid.TEL_NUMBER
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setTEL_NUMBER(String TEL_NUMBER) {
        this.TEL_NUMBER = TEL_NUMBER == null ? null : TEL_NUMBER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.ZUIDVAL
     *
     * @return the value of vendorrid.ZUIDVAL
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getZUIDVAL() {
        return ZUIDVAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.ZUIDVAL
     *
     * @param ZUIDVAL the value for vendorrid.ZUIDVAL
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setZUIDVAL(String ZUIDVAL) {
        this.ZUIDVAL = ZUIDVAL == null ? null : ZUIDVAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.PoUnit
     *
     * @return the value of vendorrid.PoUnit
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getPoUnit() {
        return poUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.PoUnit
     *
     * @param poUnit the value for vendorrid.PoUnit
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setPoUnit(String poUnit) {
        this.poUnit = poUnit == null ? null : poUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.ISbatch
     *
     * @return the value of vendorrid.ISbatch
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getISbatch() {
        return ISbatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.ISbatch
     *
     * @param ISbatch the value for vendorrid.ISbatch
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setISbatch(String ISbatch) {
        this.ISbatch = ISbatch == null ? null : ISbatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.StockName1
     *
     * @return the value of vendorrid.StockName1
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getStockName1() {
        return stockName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.StockName1
     *
     * @param stockName1 the value for vendorrid.StockName1
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setStockName1(String stockName1) {
        this.stockName1 = stockName1 == null ? null : stockName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.StockName2
     *
     * @return the value of vendorrid.StockName2
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getStockName2() {
        return stockName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.StockName2
     *
     * @param stockName2 the value for vendorrid.StockName2
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setStockName2(String stockName2) {
        this.stockName2 = stockName2 == null ? null : stockName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.EFNO
     *
     * @return the value of vendorrid.EFNO
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getEFNO() {
        return EFNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.EFNO
     *
     * @param EFNO the value for vendorrid.EFNO
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setEFNO(String EFNO) {
        this.EFNO = EFNO == null ? null : EFNO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.PATH
     *
     * @return the value of vendorrid.PATH
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getPATH() {
        return PATH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.PATH
     *
     * @param PATH the value for vendorrid.PATH
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setPATH(String PATH) {
        this.PATH = PATH == null ? null : PATH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.STGE_LOC
     *
     * @return the value of vendorrid.STGE_LOC
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getSTGE_LOC() {
        return STGE_LOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.STGE_LOC
     *
     * @param STGE_LOC the value for vendorrid.STGE_LOC
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setSTGE_LOC(String STGE_LOC) {
        this.STGE_LOC = STGE_LOC == null ? null : STGE_LOC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.xqty
     *
     * @return the value of vendorrid.xqty
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public Integer getXqty() {
        return xqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.xqty
     *
     * @param xqty the value for vendorrid.xqty
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setXqty(Integer xqty) {
        this.xqty = xqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.UpHTMES
     *
     * @return the value of vendorrid.UpHTMES
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public String getUpHTMES() {
        return upHTMES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.UpHTMES
     *
     * @param upHTMES the value for vendorrid.UpHTMES
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setUpHTMES(String upHTMES) {
        this.upHTMES = upHTMES == null ? null : upHTMES.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendorrid.UpHTMESDATE
     *
     * @return the value of vendorrid.UpHTMESDATE
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public Date getUpHTMESDATE() {
        return upHTMESDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendorrid.UpHTMESDATE
     *
     * @param upHTMESDATE the value for vendorrid.UpHTMESDATE
     *
     * @mbggenerated Mon Nov 21 14:31:42 CST 2022
     */
    public void setUpHTMESDATE(Date upHTMESDATE) {
        this.upHTMESDATE = upHTMESDATE;
    }
}