package ht.model.model108;

import java.util.Date;

public class FactoryResourceBases {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FactoryResourceBases.ID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private String ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FactoryResourceBases.Sequence
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Short sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FactoryResourceBases.IsDeleted
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FactoryResourceBases.BatchSchedulingAlarmReactionTemplateID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private String batchSchedulingAlarmReactionTemplateID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FactoryResourceBases.Efficiency
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Double efficiency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FactoryResourceBases.ReservationRecalculationTypeEnum
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Short reservationRecalculationTypeEnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FactoryResourceBases.Factory_ID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private String factory_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FactoryResourceBases.AreaParent_ID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private String areaParent_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FactoryResourceBases.RemainingQuantityCalculationEnum
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Short remainingQuantityCalculationEnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FactoryResourceBases.AuditData_ModifiedUserID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private String auditData_ModifiedUserID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FactoryResourceBases.AuditData_CreatedUserID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private String auditData_CreatedUserID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FactoryResourceBases.AuditData_CreatedDate_BaseDateTimeUTC
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Date auditData_CreatedDate_BaseDateTimeUTC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FactoryResourceBases.AuditData_ModifiedDate_BaseDateTimeUTC
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Date auditData_ModifiedDate_BaseDateTimeUTC;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FactoryResourceBases.ID
     *
     * @return the value of FactoryResourceBases.ID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public String getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FactoryResourceBases.ID
     *
     * @param ID the value for FactoryResourceBases.ID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setID(String ID) {
        this.ID = ID == null ? null : ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FactoryResourceBases.Sequence
     *
     * @return the value of FactoryResourceBases.Sequence
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Short getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FactoryResourceBases.Sequence
     *
     * @param sequence the value for FactoryResourceBases.Sequence
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setSequence(Short sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FactoryResourceBases.IsDeleted
     *
     * @return the value of FactoryResourceBases.IsDeleted
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FactoryResourceBases.IsDeleted
     *
     * @param isDeleted the value for FactoryResourceBases.IsDeleted
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FactoryResourceBases.BatchSchedulingAlarmReactionTemplateID
     *
     * @return the value of FactoryResourceBases.BatchSchedulingAlarmReactionTemplateID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public String getBatchSchedulingAlarmReactionTemplateID() {
        return batchSchedulingAlarmReactionTemplateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FactoryResourceBases.BatchSchedulingAlarmReactionTemplateID
     *
     * @param batchSchedulingAlarmReactionTemplateID the value for FactoryResourceBases.BatchSchedulingAlarmReactionTemplateID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setBatchSchedulingAlarmReactionTemplateID(String batchSchedulingAlarmReactionTemplateID) {
        this.batchSchedulingAlarmReactionTemplateID = batchSchedulingAlarmReactionTemplateID == null ? null : batchSchedulingAlarmReactionTemplateID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FactoryResourceBases.Efficiency
     *
     * @return the value of FactoryResourceBases.Efficiency
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Double getEfficiency() {
        return efficiency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FactoryResourceBases.Efficiency
     *
     * @param efficiency the value for FactoryResourceBases.Efficiency
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setEfficiency(Double efficiency) {
        this.efficiency = efficiency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FactoryResourceBases.ReservationRecalculationTypeEnum
     *
     * @return the value of FactoryResourceBases.ReservationRecalculationTypeEnum
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Short getReservationRecalculationTypeEnum() {
        return reservationRecalculationTypeEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FactoryResourceBases.ReservationRecalculationTypeEnum
     *
     * @param reservationRecalculationTypeEnum the value for FactoryResourceBases.ReservationRecalculationTypeEnum
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setReservationRecalculationTypeEnum(Short reservationRecalculationTypeEnum) {
        this.reservationRecalculationTypeEnum = reservationRecalculationTypeEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FactoryResourceBases.Factory_ID
     *
     * @return the value of FactoryResourceBases.Factory_ID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public String getFactory_ID() {
        return factory_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FactoryResourceBases.Factory_ID
     *
     * @param factory_ID the value for FactoryResourceBases.Factory_ID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setFactory_ID(String factory_ID) {
        this.factory_ID = factory_ID == null ? null : factory_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FactoryResourceBases.AreaParent_ID
     *
     * @return the value of FactoryResourceBases.AreaParent_ID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public String getAreaParent_ID() {
        return areaParent_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FactoryResourceBases.AreaParent_ID
     *
     * @param areaParent_ID the value for FactoryResourceBases.AreaParent_ID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setAreaParent_ID(String areaParent_ID) {
        this.areaParent_ID = areaParent_ID == null ? null : areaParent_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FactoryResourceBases.RemainingQuantityCalculationEnum
     *
     * @return the value of FactoryResourceBases.RemainingQuantityCalculationEnum
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Short getRemainingQuantityCalculationEnum() {
        return remainingQuantityCalculationEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FactoryResourceBases.RemainingQuantityCalculationEnum
     *
     * @param remainingQuantityCalculationEnum the value for FactoryResourceBases.RemainingQuantityCalculationEnum
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setRemainingQuantityCalculationEnum(Short remainingQuantityCalculationEnum) {
        this.remainingQuantityCalculationEnum = remainingQuantityCalculationEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FactoryResourceBases.AuditData_ModifiedUserID
     *
     * @return the value of FactoryResourceBases.AuditData_ModifiedUserID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public String getAuditData_ModifiedUserID() {
        return auditData_ModifiedUserID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FactoryResourceBases.AuditData_ModifiedUserID
     *
     * @param auditData_ModifiedUserID the value for FactoryResourceBases.AuditData_ModifiedUserID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setAuditData_ModifiedUserID(String auditData_ModifiedUserID) {
        this.auditData_ModifiedUserID = auditData_ModifiedUserID == null ? null : auditData_ModifiedUserID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FactoryResourceBases.AuditData_CreatedUserID
     *
     * @return the value of FactoryResourceBases.AuditData_CreatedUserID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public String getAuditData_CreatedUserID() {
        return auditData_CreatedUserID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FactoryResourceBases.AuditData_CreatedUserID
     *
     * @param auditData_CreatedUserID the value for FactoryResourceBases.AuditData_CreatedUserID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setAuditData_CreatedUserID(String auditData_CreatedUserID) {
        this.auditData_CreatedUserID = auditData_CreatedUserID == null ? null : auditData_CreatedUserID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FactoryResourceBases.AuditData_CreatedDate_BaseDateTimeUTC
     *
     * @return the value of FactoryResourceBases.AuditData_CreatedDate_BaseDateTimeUTC
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Date getAuditData_CreatedDate_BaseDateTimeUTC() {
        return auditData_CreatedDate_BaseDateTimeUTC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FactoryResourceBases.AuditData_CreatedDate_BaseDateTimeUTC
     *
     * @param auditData_CreatedDate_BaseDateTimeUTC the value for FactoryResourceBases.AuditData_CreatedDate_BaseDateTimeUTC
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setAuditData_CreatedDate_BaseDateTimeUTC(Date auditData_CreatedDate_BaseDateTimeUTC) {
        this.auditData_CreatedDate_BaseDateTimeUTC = auditData_CreatedDate_BaseDateTimeUTC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FactoryResourceBases.AuditData_ModifiedDate_BaseDateTimeUTC
     *
     * @return the value of FactoryResourceBases.AuditData_ModifiedDate_BaseDateTimeUTC
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Date getAuditData_ModifiedDate_BaseDateTimeUTC() {
        return auditData_ModifiedDate_BaseDateTimeUTC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FactoryResourceBases.AuditData_ModifiedDate_BaseDateTimeUTC
     *
     * @param auditData_ModifiedDate_BaseDateTimeUTC the value for FactoryResourceBases.AuditData_ModifiedDate_BaseDateTimeUTC
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setAuditData_ModifiedDate_BaseDateTimeUTC(Date auditData_ModifiedDate_BaseDateTimeUTC) {
        this.auditData_ModifiedDate_BaseDateTimeUTC = auditData_ModifiedDate_BaseDateTimeUTC;
    }
}