package ht.model.model108;

public class StockLocations {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column StockLocations.ID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private String ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column StockLocations.SortNumber
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Integer sortNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column StockLocations.IsDryStorage
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Boolean isDryStorage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column StockLocations.PosX
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Double posX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column StockLocations.PosY
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Double posY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column StockLocations.SizeX
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Double sizeX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column StockLocations.SizeY
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Double sizeY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column StockLocations.SizeZ
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Double sizeZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column StockLocations.Angle
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private Double angle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column StockLocations.ParentStockLocationID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private String parentStockLocationID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column StockLocations.StockResourceBaseID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    private String stockResourceBaseID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column StockLocations.ID
     *
     * @return the value of StockLocations.ID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public String getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column StockLocations.ID
     *
     * @param ID the value for StockLocations.ID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setID(String ID) {
        this.ID = ID == null ? null : ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column StockLocations.SortNumber
     *
     * @return the value of StockLocations.SortNumber
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Integer getSortNumber() {
        return sortNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column StockLocations.SortNumber
     *
     * @param sortNumber the value for StockLocations.SortNumber
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setSortNumber(Integer sortNumber) {
        this.sortNumber = sortNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column StockLocations.IsDryStorage
     *
     * @return the value of StockLocations.IsDryStorage
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Boolean getIsDryStorage() {
        return isDryStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column StockLocations.IsDryStorage
     *
     * @param isDryStorage the value for StockLocations.IsDryStorage
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setIsDryStorage(Boolean isDryStorage) {
        this.isDryStorage = isDryStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column StockLocations.PosX
     *
     * @return the value of StockLocations.PosX
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Double getPosX() {
        return posX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column StockLocations.PosX
     *
     * @param posX the value for StockLocations.PosX
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setPosX(Double posX) {
        this.posX = posX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column StockLocations.PosY
     *
     * @return the value of StockLocations.PosY
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Double getPosY() {
        return posY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column StockLocations.PosY
     *
     * @param posY the value for StockLocations.PosY
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setPosY(Double posY) {
        this.posY = posY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column StockLocations.SizeX
     *
     * @return the value of StockLocations.SizeX
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Double getSizeX() {
        return sizeX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column StockLocations.SizeX
     *
     * @param sizeX the value for StockLocations.SizeX
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setSizeX(Double sizeX) {
        this.sizeX = sizeX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column StockLocations.SizeY
     *
     * @return the value of StockLocations.SizeY
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Double getSizeY() {
        return sizeY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column StockLocations.SizeY
     *
     * @param sizeY the value for StockLocations.SizeY
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setSizeY(Double sizeY) {
        this.sizeY = sizeY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column StockLocations.SizeZ
     *
     * @return the value of StockLocations.SizeZ
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Double getSizeZ() {
        return sizeZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column StockLocations.SizeZ
     *
     * @param sizeZ the value for StockLocations.SizeZ
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setSizeZ(Double sizeZ) {
        this.sizeZ = sizeZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column StockLocations.Angle
     *
     * @return the value of StockLocations.Angle
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public Double getAngle() {
        return angle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column StockLocations.Angle
     *
     * @param angle the value for StockLocations.Angle
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setAngle(Double angle) {
        this.angle = angle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column StockLocations.ParentStockLocationID
     *
     * @return the value of StockLocations.ParentStockLocationID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public String getParentStockLocationID() {
        return parentStockLocationID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column StockLocations.ParentStockLocationID
     *
     * @param parentStockLocationID the value for StockLocations.ParentStockLocationID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setParentStockLocationID(String parentStockLocationID) {
        this.parentStockLocationID = parentStockLocationID == null ? null : parentStockLocationID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column StockLocations.StockResourceBaseID
     *
     * @return the value of StockLocations.StockResourceBaseID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public String getStockResourceBaseID() {
        return stockResourceBaseID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column StockLocations.StockResourceBaseID
     *
     * @param stockResourceBaseID the value for StockLocations.StockResourceBaseID
     *
     * @mbggenerated Mon Nov 21 13:51:24 CST 2022
     */
    public void setStockResourceBaseID(String stockResourceBaseID) {
        this.stockResourceBaseID = stockResourceBaseID == null ? null : stockResourceBaseID.trim();
    }
}