package ht.model.model33;

import java.util.Date;

public class NotFinishSO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotFinishSO.id
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotFinishSO.so
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String so;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotFinishSO.plant
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String plant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotFinishSO.pn
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String pn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotFinishSO.bom
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String bom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotFinishSO.needQty
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String needQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotFinishSO.gotQty
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String gotQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotFinishSO.stock
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotFinishSO.inventory
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String inventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotFinishSO.soStartDate
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String soStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotFinishSO.createdate
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotFinishSO.id
     *
     * @return the value of NotFinishSO.id
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotFinishSO.id
     *
     * @param id the value for NotFinishSO.id
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotFinishSO.so
     *
     * @return the value of NotFinishSO.so
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getSo() {
        return so;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotFinishSO.so
     *
     * @param so the value for NotFinishSO.so
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setSo(String so) {
        this.so = so == null ? null : so.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotFinishSO.plant
     *
     * @return the value of NotFinishSO.plant
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getPlant() {
        return plant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotFinishSO.plant
     *
     * @param plant the value for NotFinishSO.plant
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setPlant(String plant) {
        this.plant = plant == null ? null : plant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotFinishSO.pn
     *
     * @return the value of NotFinishSO.pn
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getPn() {
        return pn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotFinishSO.pn
     *
     * @param pn the value for NotFinishSO.pn
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setPn(String pn) {
        this.pn = pn == null ? null : pn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotFinishSO.bom
     *
     * @return the value of NotFinishSO.bom
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getBom() {
        return bom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotFinishSO.bom
     *
     * @param bom the value for NotFinishSO.bom
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setBom(String bom) {
        this.bom = bom == null ? null : bom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotFinishSO.needQty
     *
     * @return the value of NotFinishSO.needQty
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getNeedQty() {
        return needQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotFinishSO.needQty
     *
     * @param needQty the value for NotFinishSO.needQty
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setNeedQty(String needQty) {
        this.needQty = needQty == null ? null : needQty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotFinishSO.gotQty
     *
     * @return the value of NotFinishSO.gotQty
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getGotQty() {
        return gotQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotFinishSO.gotQty
     *
     * @param gotQty the value for NotFinishSO.gotQty
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setGotQty(String gotQty) {
        this.gotQty = gotQty == null ? null : gotQty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotFinishSO.stock
     *
     * @return the value of NotFinishSO.stock
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotFinishSO.stock
     *
     * @param stock the value for NotFinishSO.stock
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setStock(String stock) {
        this.stock = stock == null ? null : stock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotFinishSO.inventory
     *
     * @return the value of NotFinishSO.inventory
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotFinishSO.inventory
     *
     * @param inventory the value for NotFinishSO.inventory
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setInventory(String inventory) {
        this.inventory = inventory == null ? null : inventory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotFinishSO.soStartDate
     *
     * @return the value of NotFinishSO.soStartDate
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getSoStartDate() {
        return soStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotFinishSO.soStartDate
     *
     * @param soStartDate the value for NotFinishSO.soStartDate
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setSoStartDate(String soStartDate) {
        this.soStartDate = soStartDate == null ? null : soStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotFinishSO.createdate
     *
     * @return the value of NotFinishSO.createdate
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotFinishSO.createdate
     *
     * @param createdate the value for NotFinishSO.createdate
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}