package ht.model.model33;

import java.util.Date;

public class ToReceiveWarehouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.id
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.GRN
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String GRN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.ItemNumber
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String itemNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.GRNQuantity
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String GRNQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.ReceivingLocation
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String receivingLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.ProductionTime
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String productionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.AegisQualify
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String aegisQualify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.SAPQualify
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String SAPQualify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.WaitTimeToMainbin
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String waitTimeToMainbin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.ReturnWarehouseTime
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String returnWarehouseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.plant
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String plant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.UID
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.Type
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.Sequence
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.createdate
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ToReceiveWarehouse.closeDate
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    private Date closeDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.id
     *
     * @return the value of ToReceiveWarehouse.id
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.id
     *
     * @param id the value for ToReceiveWarehouse.id
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.GRN
     *
     * @return the value of ToReceiveWarehouse.GRN
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getGRN() {
        return GRN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.GRN
     *
     * @param GRN the value for ToReceiveWarehouse.GRN
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setGRN(String GRN) {
        this.GRN = GRN == null ? null : GRN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.ItemNumber
     *
     * @return the value of ToReceiveWarehouse.ItemNumber
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getItemNumber() {
        return itemNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.ItemNumber
     *
     * @param itemNumber the value for ToReceiveWarehouse.ItemNumber
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setItemNumber(String itemNumber) {
        this.itemNumber = itemNumber == null ? null : itemNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.GRNQuantity
     *
     * @return the value of ToReceiveWarehouse.GRNQuantity
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getGRNQuantity() {
        return GRNQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.GRNQuantity
     *
     * @param GRNQuantity the value for ToReceiveWarehouse.GRNQuantity
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setGRNQuantity(String GRNQuantity) {
        this.GRNQuantity = GRNQuantity == null ? null : GRNQuantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.ReceivingLocation
     *
     * @return the value of ToReceiveWarehouse.ReceivingLocation
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getReceivingLocation() {
        return receivingLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.ReceivingLocation
     *
     * @param receivingLocation the value for ToReceiveWarehouse.ReceivingLocation
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setReceivingLocation(String receivingLocation) {
        this.receivingLocation = receivingLocation == null ? null : receivingLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.ProductionTime
     *
     * @return the value of ToReceiveWarehouse.ProductionTime
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getProductionTime() {
        return productionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.ProductionTime
     *
     * @param productionTime the value for ToReceiveWarehouse.ProductionTime
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setProductionTime(String productionTime) {
        this.productionTime = productionTime == null ? null : productionTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.AegisQualify
     *
     * @return the value of ToReceiveWarehouse.AegisQualify
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getAegisQualify() {
        return aegisQualify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.AegisQualify
     *
     * @param aegisQualify the value for ToReceiveWarehouse.AegisQualify
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setAegisQualify(String aegisQualify) {
        this.aegisQualify = aegisQualify == null ? null : aegisQualify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.SAPQualify
     *
     * @return the value of ToReceiveWarehouse.SAPQualify
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getSAPQualify() {
        return SAPQualify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.SAPQualify
     *
     * @param SAPQualify the value for ToReceiveWarehouse.SAPQualify
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setSAPQualify(String SAPQualify) {
        this.SAPQualify = SAPQualify == null ? null : SAPQualify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.WaitTimeToMainbin
     *
     * @return the value of ToReceiveWarehouse.WaitTimeToMainbin
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getWaitTimeToMainbin() {
        return waitTimeToMainbin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.WaitTimeToMainbin
     *
     * @param waitTimeToMainbin the value for ToReceiveWarehouse.WaitTimeToMainbin
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setWaitTimeToMainbin(String waitTimeToMainbin) {
        this.waitTimeToMainbin = waitTimeToMainbin == null ? null : waitTimeToMainbin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.ReturnWarehouseTime
     *
     * @return the value of ToReceiveWarehouse.ReturnWarehouseTime
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getReturnWarehouseTime() {
        return returnWarehouseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.ReturnWarehouseTime
     *
     * @param returnWarehouseTime the value for ToReceiveWarehouse.ReturnWarehouseTime
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setReturnWarehouseTime(String returnWarehouseTime) {
        this.returnWarehouseTime = returnWarehouseTime == null ? null : returnWarehouseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.plant
     *
     * @return the value of ToReceiveWarehouse.plant
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getPlant() {
        return plant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.plant
     *
     * @param plant the value for ToReceiveWarehouse.plant
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setPlant(String plant) {
        this.plant = plant == null ? null : plant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.UID
     *
     * @return the value of ToReceiveWarehouse.UID
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.UID
     *
     * @param UID the value for ToReceiveWarehouse.UID
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setUID(String UID) {
        this.UID = UID == null ? null : UID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.Type
     *
     * @return the value of ToReceiveWarehouse.Type
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.Type
     *
     * @param type the value for ToReceiveWarehouse.Type
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.Sequence
     *
     * @return the value of ToReceiveWarehouse.Sequence
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.Sequence
     *
     * @param sequence the value for ToReceiveWarehouse.Sequence
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.createdate
     *
     * @return the value of ToReceiveWarehouse.createdate
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.createdate
     *
     * @param createdate the value for ToReceiveWarehouse.createdate
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ToReceiveWarehouse.closeDate
     *
     * @return the value of ToReceiveWarehouse.closeDate
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public Date getCloseDate() {
        return closeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ToReceiveWarehouse.closeDate
     *
     * @param closeDate the value for ToReceiveWarehouse.closeDate
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setCloseDate(Date closeDate) {
        this.closeDate = closeDate;
    }
}