package ht.model.model33;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UrgentMaterialCheckNotOCRExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public UrgentMaterialCheckNotOCRExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGRNIsNull() {
            addCriterion("GRN is null");
            return (Criteria) this;
        }

        public Criteria andGRNIsNotNull() {
            addCriterion("GRN is not null");
            return (Criteria) this;
        }

        public Criteria andGRNEqualTo(String value) {
            addCriterion("GRN =", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNNotEqualTo(String value) {
            addCriterion("GRN <>", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNGreaterThan(String value) {
            addCriterion("GRN >", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNGreaterThanOrEqualTo(String value) {
            addCriterion("GRN >=", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNLessThan(String value) {
            addCriterion("GRN <", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNLessThanOrEqualTo(String value) {
            addCriterion("GRN <=", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNLike(String value) {
            addCriterion("GRN like", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNNotLike(String value) {
            addCriterion("GRN not like", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNIn(List<String> values) {
            addCriterion("GRN in", values, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNNotIn(List<String> values) {
            addCriterion("GRN not in", values, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNBetween(String value1, String value2) {
            addCriterion("GRN between", value1, value2, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNNotBetween(String value1, String value2) {
            addCriterion("GRN not between", value1, value2, "GRN");
            return (Criteria) this;
        }

        public Criteria andItemNumberIsNull() {
            addCriterion("ItemNumber is null");
            return (Criteria) this;
        }

        public Criteria andItemNumberIsNotNull() {
            addCriterion("ItemNumber is not null");
            return (Criteria) this;
        }

        public Criteria andItemNumberEqualTo(String value) {
            addCriterion("ItemNumber =", value, "itemNumber");
            return (Criteria) this;
        }

        public Criteria andItemNumberNotEqualTo(String value) {
            addCriterion("ItemNumber <>", value, "itemNumber");
            return (Criteria) this;
        }

        public Criteria andItemNumberGreaterThan(String value) {
            addCriterion("ItemNumber >", value, "itemNumber");
            return (Criteria) this;
        }

        public Criteria andItemNumberGreaterThanOrEqualTo(String value) {
            addCriterion("ItemNumber >=", value, "itemNumber");
            return (Criteria) this;
        }

        public Criteria andItemNumberLessThan(String value) {
            addCriterion("ItemNumber <", value, "itemNumber");
            return (Criteria) this;
        }

        public Criteria andItemNumberLessThanOrEqualTo(String value) {
            addCriterion("ItemNumber <=", value, "itemNumber");
            return (Criteria) this;
        }

        public Criteria andItemNumberLike(String value) {
            addCriterion("ItemNumber like", value, "itemNumber");
            return (Criteria) this;
        }

        public Criteria andItemNumberNotLike(String value) {
            addCriterion("ItemNumber not like", value, "itemNumber");
            return (Criteria) this;
        }

        public Criteria andItemNumberIn(List<String> values) {
            addCriterion("ItemNumber in", values, "itemNumber");
            return (Criteria) this;
        }

        public Criteria andItemNumberNotIn(List<String> values) {
            addCriterion("ItemNumber not in", values, "itemNumber");
            return (Criteria) this;
        }

        public Criteria andItemNumberBetween(String value1, String value2) {
            addCriterion("ItemNumber between", value1, value2, "itemNumber");
            return (Criteria) this;
        }

        public Criteria andItemNumberNotBetween(String value1, String value2) {
            addCriterion("ItemNumber not between", value1, value2, "itemNumber");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationIsNull() {
            addCriterion("ReceivingLocation is null");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationIsNotNull() {
            addCriterion("ReceivingLocation is not null");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationEqualTo(String value) {
            addCriterion("ReceivingLocation =", value, "receivingLocation");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationNotEqualTo(String value) {
            addCriterion("ReceivingLocation <>", value, "receivingLocation");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationGreaterThan(String value) {
            addCriterion("ReceivingLocation >", value, "receivingLocation");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationGreaterThanOrEqualTo(String value) {
            addCriterion("ReceivingLocation >=", value, "receivingLocation");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationLessThan(String value) {
            addCriterion("ReceivingLocation <", value, "receivingLocation");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationLessThanOrEqualTo(String value) {
            addCriterion("ReceivingLocation <=", value, "receivingLocation");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationLike(String value) {
            addCriterion("ReceivingLocation like", value, "receivingLocation");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationNotLike(String value) {
            addCriterion("ReceivingLocation not like", value, "receivingLocation");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationIn(List<String> values) {
            addCriterion("ReceivingLocation in", values, "receivingLocation");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationNotIn(List<String> values) {
            addCriterion("ReceivingLocation not in", values, "receivingLocation");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationBetween(String value1, String value2) {
            addCriterion("ReceivingLocation between", value1, value2, "receivingLocation");
            return (Criteria) this;
        }

        public Criteria andReceivingLocationNotBetween(String value1, String value2) {
            addCriterion("ReceivingLocation not between", value1, value2, "receivingLocation");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeIsNull() {
            addCriterion("RDFinishTime is null");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeIsNotNull() {
            addCriterion("RDFinishTime is not null");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeEqualTo(String value) {
            addCriterion("RDFinishTime =", value, "RDFinishTime");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeNotEqualTo(String value) {
            addCriterion("RDFinishTime <>", value, "RDFinishTime");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeGreaterThan(String value) {
            addCriterion("RDFinishTime >", value, "RDFinishTime");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeGreaterThanOrEqualTo(String value) {
            addCriterion("RDFinishTime >=", value, "RDFinishTime");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeLessThan(String value) {
            addCriterion("RDFinishTime <", value, "RDFinishTime");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeLessThanOrEqualTo(String value) {
            addCriterion("RDFinishTime <=", value, "RDFinishTime");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeLike(String value) {
            addCriterion("RDFinishTime like", value, "RDFinishTime");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeNotLike(String value) {
            addCriterion("RDFinishTime not like", value, "RDFinishTime");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeIn(List<String> values) {
            addCriterion("RDFinishTime in", values, "RDFinishTime");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeNotIn(List<String> values) {
            addCriterion("RDFinishTime not in", values, "RDFinishTime");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeBetween(String value1, String value2) {
            addCriterion("RDFinishTime between", value1, value2, "RDFinishTime");
            return (Criteria) this;
        }

        public Criteria andRDFinishTimeNotBetween(String value1, String value2) {
            addCriterion("RDFinishTime not between", value1, value2, "RDFinishTime");
            return (Criteria) this;
        }

        public Criteria andProductionTimeIsNull() {
            addCriterion("ProductionTime is null");
            return (Criteria) this;
        }

        public Criteria andProductionTimeIsNotNull() {
            addCriterion("ProductionTime is not null");
            return (Criteria) this;
        }

        public Criteria andProductionTimeEqualTo(String value) {
            addCriterion("ProductionTime =", value, "productionTime");
            return (Criteria) this;
        }

        public Criteria andProductionTimeNotEqualTo(String value) {
            addCriterion("ProductionTime <>", value, "productionTime");
            return (Criteria) this;
        }

        public Criteria andProductionTimeGreaterThan(String value) {
            addCriterion("ProductionTime >", value, "productionTime");
            return (Criteria) this;
        }

        public Criteria andProductionTimeGreaterThanOrEqualTo(String value) {
            addCriterion("ProductionTime >=", value, "productionTime");
            return (Criteria) this;
        }

        public Criteria andProductionTimeLessThan(String value) {
            addCriterion("ProductionTime <", value, "productionTime");
            return (Criteria) this;
        }

        public Criteria andProductionTimeLessThanOrEqualTo(String value) {
            addCriterion("ProductionTime <=", value, "productionTime");
            return (Criteria) this;
        }

        public Criteria andProductionTimeLike(String value) {
            addCriterion("ProductionTime like", value, "productionTime");
            return (Criteria) this;
        }

        public Criteria andProductionTimeNotLike(String value) {
            addCriterion("ProductionTime not like", value, "productionTime");
            return (Criteria) this;
        }

        public Criteria andProductionTimeIn(List<String> values) {
            addCriterion("ProductionTime in", values, "productionTime");
            return (Criteria) this;
        }

        public Criteria andProductionTimeNotIn(List<String> values) {
            addCriterion("ProductionTime not in", values, "productionTime");
            return (Criteria) this;
        }

        public Criteria andProductionTimeBetween(String value1, String value2) {
            addCriterion("ProductionTime between", value1, value2, "productionTime");
            return (Criteria) this;
        }

        public Criteria andProductionTimeNotBetween(String value1, String value2) {
            addCriterion("ProductionTime not between", value1, value2, "productionTime");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeIsNull() {
            addCriterion("IQCGetTime is null");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeIsNotNull() {
            addCriterion("IQCGetTime is not null");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeEqualTo(String value) {
            addCriterion("IQCGetTime =", value, "IQCGetTime");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeNotEqualTo(String value) {
            addCriterion("IQCGetTime <>", value, "IQCGetTime");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeGreaterThan(String value) {
            addCriterion("IQCGetTime >", value, "IQCGetTime");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeGreaterThanOrEqualTo(String value) {
            addCriterion("IQCGetTime >=", value, "IQCGetTime");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeLessThan(String value) {
            addCriterion("IQCGetTime <", value, "IQCGetTime");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeLessThanOrEqualTo(String value) {
            addCriterion("IQCGetTime <=", value, "IQCGetTime");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeLike(String value) {
            addCriterion("IQCGetTime like", value, "IQCGetTime");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeNotLike(String value) {
            addCriterion("IQCGetTime not like", value, "IQCGetTime");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeIn(List<String> values) {
            addCriterion("IQCGetTime in", values, "IQCGetTime");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeNotIn(List<String> values) {
            addCriterion("IQCGetTime not in", values, "IQCGetTime");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeBetween(String value1, String value2) {
            addCriterion("IQCGetTime between", value1, value2, "IQCGetTime");
            return (Criteria) this;
        }

        public Criteria andIQCGetTimeNotBetween(String value1, String value2) {
            addCriterion("IQCGetTime not between", value1, value2, "IQCGetTime");
            return (Criteria) this;
        }

        public Criteria andHourIsNull() {
            addCriterion("hour is null");
            return (Criteria) this;
        }

        public Criteria andHourIsNotNull() {
            addCriterion("hour is not null");
            return (Criteria) this;
        }

        public Criteria andHourEqualTo(Integer value) {
            addCriterion("hour =", value, "hour");
            return (Criteria) this;
        }

        public Criteria andHourNotEqualTo(Integer value) {
            addCriterion("hour <>", value, "hour");
            return (Criteria) this;
        }

        public Criteria andHourGreaterThan(Integer value) {
            addCriterion("hour >", value, "hour");
            return (Criteria) this;
        }

        public Criteria andHourGreaterThanOrEqualTo(Integer value) {
            addCriterion("hour >=", value, "hour");
            return (Criteria) this;
        }

        public Criteria andHourLessThan(Integer value) {
            addCriterion("hour <", value, "hour");
            return (Criteria) this;
        }

        public Criteria andHourLessThanOrEqualTo(Integer value) {
            addCriterion("hour <=", value, "hour");
            return (Criteria) this;
        }

        public Criteria andHourIn(List<Integer> values) {
            addCriterion("hour in", values, "hour");
            return (Criteria) this;
        }

        public Criteria andHourNotIn(List<Integer> values) {
            addCriterion("hour not in", values, "hour");
            return (Criteria) this;
        }

        public Criteria andHourBetween(Integer value1, Integer value2) {
            addCriterion("hour between", value1, value2, "hour");
            return (Criteria) this;
        }

        public Criteria andHourNotBetween(Integer value1, Integer value2) {
            addCriterion("hour not between", value1, value2, "hour");
            return (Criteria) this;
        }

        public Criteria andMinIsNull() {
            addCriterion("min is null");
            return (Criteria) this;
        }

        public Criteria andMinIsNotNull() {
            addCriterion("min is not null");
            return (Criteria) this;
        }

        public Criteria andMinEqualTo(Integer value) {
            addCriterion("min =", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinNotEqualTo(Integer value) {
            addCriterion("min <>", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinGreaterThan(Integer value) {
            addCriterion("min >", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinGreaterThanOrEqualTo(Integer value) {
            addCriterion("min >=", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinLessThan(Integer value) {
            addCriterion("min <", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinLessThanOrEqualTo(Integer value) {
            addCriterion("min <=", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinIn(List<Integer> values) {
            addCriterion("min in", values, "min");
            return (Criteria) this;
        }

        public Criteria andMinNotIn(List<Integer> values) {
            addCriterion("min not in", values, "min");
            return (Criteria) this;
        }

        public Criteria andMinBetween(Integer value1, Integer value2) {
            addCriterion("min between", value1, value2, "min");
            return (Criteria) this;
        }

        public Criteria andMinNotBetween(Integer value1, Integer value2) {
            addCriterion("min not between", value1, value2, "min");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeIsNull() {
            addCriterion("IQCCheckWaitTime is null");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeIsNotNull() {
            addCriterion("IQCCheckWaitTime is not null");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeEqualTo(String value) {
            addCriterion("IQCCheckWaitTime =", value, "IQCCheckWaitTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeNotEqualTo(String value) {
            addCriterion("IQCCheckWaitTime <>", value, "IQCCheckWaitTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeGreaterThan(String value) {
            addCriterion("IQCCheckWaitTime >", value, "IQCCheckWaitTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeGreaterThanOrEqualTo(String value) {
            addCriterion("IQCCheckWaitTime >=", value, "IQCCheckWaitTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeLessThan(String value) {
            addCriterion("IQCCheckWaitTime <", value, "IQCCheckWaitTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeLessThanOrEqualTo(String value) {
            addCriterion("IQCCheckWaitTime <=", value, "IQCCheckWaitTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeLike(String value) {
            addCriterion("IQCCheckWaitTime like", value, "IQCCheckWaitTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeNotLike(String value) {
            addCriterion("IQCCheckWaitTime not like", value, "IQCCheckWaitTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeIn(List<String> values) {
            addCriterion("IQCCheckWaitTime in", values, "IQCCheckWaitTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeNotIn(List<String> values) {
            addCriterion("IQCCheckWaitTime not in", values, "IQCCheckWaitTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeBetween(String value1, String value2) {
            addCriterion("IQCCheckWaitTime between", value1, value2, "IQCCheckWaitTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckWaitTimeNotBetween(String value1, String value2) {
            addCriterion("IQCCheckWaitTime not between", value1, value2, "IQCCheckWaitTime");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeIsNull() {
            addCriterion("IQCReturnTime is null");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeIsNotNull() {
            addCriterion("IQCReturnTime is not null");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeEqualTo(String value) {
            addCriterion("IQCReturnTime =", value, "IQCReturnTime");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeNotEqualTo(String value) {
            addCriterion("IQCReturnTime <>", value, "IQCReturnTime");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeGreaterThan(String value) {
            addCriterion("IQCReturnTime >", value, "IQCReturnTime");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeGreaterThanOrEqualTo(String value) {
            addCriterion("IQCReturnTime >=", value, "IQCReturnTime");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeLessThan(String value) {
            addCriterion("IQCReturnTime <", value, "IQCReturnTime");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeLessThanOrEqualTo(String value) {
            addCriterion("IQCReturnTime <=", value, "IQCReturnTime");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeLike(String value) {
            addCriterion("IQCReturnTime like", value, "IQCReturnTime");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeNotLike(String value) {
            addCriterion("IQCReturnTime not like", value, "IQCReturnTime");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeIn(List<String> values) {
            addCriterion("IQCReturnTime in", values, "IQCReturnTime");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeNotIn(List<String> values) {
            addCriterion("IQCReturnTime not in", values, "IQCReturnTime");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeBetween(String value1, String value2) {
            addCriterion("IQCReturnTime between", value1, value2, "IQCReturnTime");
            return (Criteria) this;
        }

        public Criteria andIQCReturnTimeNotBetween(String value1, String value2) {
            addCriterion("IQCReturnTime not between", value1, value2, "IQCReturnTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeIsNull() {
            addCriterion("IQCCheckTime is null");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeIsNotNull() {
            addCriterion("IQCCheckTime is not null");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeEqualTo(String value) {
            addCriterion("IQCCheckTime =", value, "IQCCheckTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeNotEqualTo(String value) {
            addCriterion("IQCCheckTime <>", value, "IQCCheckTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeGreaterThan(String value) {
            addCriterion("IQCCheckTime >", value, "IQCCheckTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeGreaterThanOrEqualTo(String value) {
            addCriterion("IQCCheckTime >=", value, "IQCCheckTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeLessThan(String value) {
            addCriterion("IQCCheckTime <", value, "IQCCheckTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeLessThanOrEqualTo(String value) {
            addCriterion("IQCCheckTime <=", value, "IQCCheckTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeLike(String value) {
            addCriterion("IQCCheckTime like", value, "IQCCheckTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeNotLike(String value) {
            addCriterion("IQCCheckTime not like", value, "IQCCheckTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeIn(List<String> values) {
            addCriterion("IQCCheckTime in", values, "IQCCheckTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeNotIn(List<String> values) {
            addCriterion("IQCCheckTime not in", values, "IQCCheckTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeBetween(String value1, String value2) {
            addCriterion("IQCCheckTime between", value1, value2, "IQCCheckTime");
            return (Criteria) this;
        }

        public Criteria andIQCCheckTimeNotBetween(String value1, String value2) {
            addCriterion("IQCCheckTime not between", value1, value2, "IQCCheckTime");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPIsNull() {
            addCriterion("IQCUploadTimeToSAP is null");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPIsNotNull() {
            addCriterion("IQCUploadTimeToSAP is not null");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPEqualTo(String value) {
            addCriterion("IQCUploadTimeToSAP =", value, "IQCUploadTimeToSAP");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPNotEqualTo(String value) {
            addCriterion("IQCUploadTimeToSAP <>", value, "IQCUploadTimeToSAP");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPGreaterThan(String value) {
            addCriterion("IQCUploadTimeToSAP >", value, "IQCUploadTimeToSAP");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPGreaterThanOrEqualTo(String value) {
            addCriterion("IQCUploadTimeToSAP >=", value, "IQCUploadTimeToSAP");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPLessThan(String value) {
            addCriterion("IQCUploadTimeToSAP <", value, "IQCUploadTimeToSAP");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPLessThanOrEqualTo(String value) {
            addCriterion("IQCUploadTimeToSAP <=", value, "IQCUploadTimeToSAP");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPLike(String value) {
            addCriterion("IQCUploadTimeToSAP like", value, "IQCUploadTimeToSAP");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPNotLike(String value) {
            addCriterion("IQCUploadTimeToSAP not like", value, "IQCUploadTimeToSAP");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPIn(List<String> values) {
            addCriterion("IQCUploadTimeToSAP in", values, "IQCUploadTimeToSAP");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPNotIn(List<String> values) {
            addCriterion("IQCUploadTimeToSAP not in", values, "IQCUploadTimeToSAP");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPBetween(String value1, String value2) {
            addCriterion("IQCUploadTimeToSAP between", value1, value2, "IQCUploadTimeToSAP");
            return (Criteria) this;
        }

        public Criteria andIQCUploadTimeToSAPNotBetween(String value1, String value2) {
            addCriterion("IQCUploadTimeToSAP not between", value1, value2, "IQCUploadTimeToSAP");
            return (Criteria) this;
        }

        public Criteria andPlantIsNull() {
            addCriterion("plant is null");
            return (Criteria) this;
        }

        public Criteria andPlantIsNotNull() {
            addCriterion("plant is not null");
            return (Criteria) this;
        }

        public Criteria andPlantEqualTo(String value) {
            addCriterion("plant =", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotEqualTo(String value) {
            addCriterion("plant <>", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantGreaterThan(String value) {
            addCriterion("plant >", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantGreaterThanOrEqualTo(String value) {
            addCriterion("plant >=", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLessThan(String value) {
            addCriterion("plant <", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLessThanOrEqualTo(String value) {
            addCriterion("plant <=", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLike(String value) {
            addCriterion("plant like", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotLike(String value) {
            addCriterion("plant not like", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantIn(List<String> values) {
            addCriterion("plant in", values, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotIn(List<String> values) {
            addCriterion("plant not in", values, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantBetween(String value1, String value2) {
            addCriterion("plant between", value1, value2, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotBetween(String value1, String value2) {
            addCriterion("plant not between", value1, value2, "plant");
            return (Criteria) this;
        }

        public Criteria andUIDIsNull() {
            addCriterion("UID is null");
            return (Criteria) this;
        }

        public Criteria andUIDIsNotNull() {
            addCriterion("UID is not null");
            return (Criteria) this;
        }

        public Criteria andUIDEqualTo(String value) {
            addCriterion("UID =", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotEqualTo(String value) {
            addCriterion("UID <>", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDGreaterThan(String value) {
            addCriterion("UID >", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDGreaterThanOrEqualTo(String value) {
            addCriterion("UID >=", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDLessThan(String value) {
            addCriterion("UID <", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDLessThanOrEqualTo(String value) {
            addCriterion("UID <=", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDLike(String value) {
            addCriterion("UID like", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotLike(String value) {
            addCriterion("UID not like", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDIn(List<String> values) {
            addCriterion("UID in", values, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotIn(List<String> values) {
            addCriterion("UID not in", values, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDBetween(String value1, String value2) {
            addCriterion("UID between", value1, value2, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotBetween(String value1, String value2) {
            addCriterion("UID not between", value1, value2, "UID");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("Type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("Type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("Type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("Type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("Type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("Type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("Type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("Type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("Type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("Type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("Type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("Type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("Type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNull() {
            addCriterion("Sequence is null");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNotNull() {
            addCriterion("Sequence is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceEqualTo(Integer value) {
            addCriterion("Sequence =", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotEqualTo(Integer value) {
            addCriterion("Sequence <>", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThan(Integer value) {
            addCriterion("Sequence >", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThanOrEqualTo(Integer value) {
            addCriterion("Sequence >=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThan(Integer value) {
            addCriterion("Sequence <", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThanOrEqualTo(Integer value) {
            addCriterion("Sequence <=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceIn(List<Integer> values) {
            addCriterion("Sequence in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotIn(List<Integer> values) {
            addCriterion("Sequence not in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceBetween(Integer value1, Integer value2) {
            addCriterion("Sequence between", value1, value2, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotBetween(Integer value1, Integer value2) {
            addCriterion("Sequence not between", value1, value2, "sequence");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNull() {
            addCriterion("updatedate is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNotNull() {
            addCriterion("updatedate is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateEqualTo(Date value) {
            addCriterion("updatedate =", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotEqualTo(Date value) {
            addCriterion("updatedate <>", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThan(Date value) {
            addCriterion("updatedate >", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("updatedate >=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThan(Date value) {
            addCriterion("updatedate <", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
            addCriterion("updatedate <=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIn(List<Date> values) {
            addCriterion("updatedate in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotIn(List<Date> values) {
            addCriterion("updatedate not in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateBetween(Date value1, Date value2) {
            addCriterion("updatedate between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
            addCriterion("updatedate not between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createdate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createdate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createdate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createdate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createdate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createdate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createdate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createdate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createdate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createdate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createdate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createdate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andGRNDATEIsNull() {
            addCriterion("GRNDATE is null");
            return (Criteria) this;
        }

        public Criteria andGRNDATEIsNotNull() {
            addCriterion("GRNDATE is not null");
            return (Criteria) this;
        }

        public Criteria andGRNDATEEqualTo(String value) {
            addCriterion("GRNDATE =", value, "GRNDATE");
            return (Criteria) this;
        }

        public Criteria andGRNDATENotEqualTo(String value) {
            addCriterion("GRNDATE <>", value, "GRNDATE");
            return (Criteria) this;
        }

        public Criteria andGRNDATEGreaterThan(String value) {
            addCriterion("GRNDATE >", value, "GRNDATE");
            return (Criteria) this;
        }

        public Criteria andGRNDATEGreaterThanOrEqualTo(String value) {
            addCriterion("GRNDATE >=", value, "GRNDATE");
            return (Criteria) this;
        }

        public Criteria andGRNDATELessThan(String value) {
            addCriterion("GRNDATE <", value, "GRNDATE");
            return (Criteria) this;
        }

        public Criteria andGRNDATELessThanOrEqualTo(String value) {
            addCriterion("GRNDATE <=", value, "GRNDATE");
            return (Criteria) this;
        }

        public Criteria andGRNDATELike(String value) {
            addCriterion("GRNDATE like", value, "GRNDATE");
            return (Criteria) this;
        }

        public Criteria andGRNDATENotLike(String value) {
            addCriterion("GRNDATE not like", value, "GRNDATE");
            return (Criteria) this;
        }

        public Criteria andGRNDATEIn(List<String> values) {
            addCriterion("GRNDATE in", values, "GRNDATE");
            return (Criteria) this;
        }

        public Criteria andGRNDATENotIn(List<String> values) {
            addCriterion("GRNDATE not in", values, "GRNDATE");
            return (Criteria) this;
        }

        public Criteria andGRNDATEBetween(String value1, String value2) {
            addCriterion("GRNDATE between", value1, value2, "GRNDATE");
            return (Criteria) this;
        }

        public Criteria andGRNDATENotBetween(String value1, String value2) {
            addCriterion("GRNDATE not between", value1, value2, "GRNDATE");
            return (Criteria) this;
        }

        public Criteria andCloseDateIsNull() {
            addCriterion("closeDate is null");
            return (Criteria) this;
        }

        public Criteria andCloseDateIsNotNull() {
            addCriterion("closeDate is not null");
            return (Criteria) this;
        }

        public Criteria andCloseDateEqualTo(Date value) {
            addCriterion("closeDate =", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateNotEqualTo(Date value) {
            addCriterion("closeDate <>", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateGreaterThan(Date value) {
            addCriterion("closeDate >", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateGreaterThanOrEqualTo(Date value) {
            addCriterion("closeDate >=", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateLessThan(Date value) {
            addCriterion("closeDate <", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateLessThanOrEqualTo(Date value) {
            addCriterion("closeDate <=", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateIn(List<Date> values) {
            addCriterion("closeDate in", values, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateNotIn(List<Date> values) {
            addCriterion("closeDate not in", values, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateBetween(Date value1, Date value2) {
            addCriterion("closeDate between", value1, value2, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateNotBetween(Date value1, Date value2) {
            addCriterion("closeDate not between", value1, value2, "closeDate");
            return (Criteria) this;
        }

        public Criteria andSap321122IsNull() {
            addCriterion("sap321122 is null");
            return (Criteria) this;
        }

        public Criteria andSap321122IsNotNull() {
            addCriterion("sap321122 is not null");
            return (Criteria) this;
        }

        public Criteria andSap321122EqualTo(String value) {
            addCriterion("sap321122 =", value, "sap321122");
            return (Criteria) this;
        }

        public Criteria andSap321122NotEqualTo(String value) {
            addCriterion("sap321122 <>", value, "sap321122");
            return (Criteria) this;
        }

        public Criteria andSap321122GreaterThan(String value) {
            addCriterion("sap321122 >", value, "sap321122");
            return (Criteria) this;
        }

        public Criteria andSap321122GreaterThanOrEqualTo(String value) {
            addCriterion("sap321122 >=", value, "sap321122");
            return (Criteria) this;
        }

        public Criteria andSap321122LessThan(String value) {
            addCriterion("sap321122 <", value, "sap321122");
            return (Criteria) this;
        }

        public Criteria andSap321122LessThanOrEqualTo(String value) {
            addCriterion("sap321122 <=", value, "sap321122");
            return (Criteria) this;
        }

        public Criteria andSap321122Like(String value) {
            addCriterion("sap321122 like", value, "sap321122");
            return (Criteria) this;
        }

        public Criteria andSap321122NotLike(String value) {
            addCriterion("sap321122 not like", value, "sap321122");
            return (Criteria) this;
        }

        public Criteria andSap321122In(List<String> values) {
            addCriterion("sap321122 in", values, "sap321122");
            return (Criteria) this;
        }

        public Criteria andSap321122NotIn(List<String> values) {
            addCriterion("sap321122 not in", values, "sap321122");
            return (Criteria) this;
        }

        public Criteria andSap321122Between(String value1, String value2) {
            addCriterion("sap321122 between", value1, value2, "sap321122");
            return (Criteria) this;
        }

        public Criteria andSap321122NotBetween(String value1, String value2) {
            addCriterion("sap321122 not between", value1, value2, "sap321122");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 21 21:52:33 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UrgentMaterialCheckNotOCR
     *
     * @mbggenerated Mon Nov 21 21:52:33 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}